Make it blatantly clear what's online-only
NVE/regObs4 pull request #113
Opened 2021-10-26 16:51 UTC by widforss

This change throws up a popup every time the user activates
an online-only support map. It also rebases some of the
popup code, since it started to have quite a bit of copied
code.

2021-10-31 18:47 UTC, widforss commented on src/app/core/services/popup-info/popup-info.service.ts
> +    this.userSettingService.saveUserSettings(userSettings);
Ante ikke dette! Takk :)

2021-10-31 18:54 UTC, widforss commented on src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
> +  checkForInfoPopup(enabled: boolean, supportTile: SupportTile = null) {
Jeg venter med dette. I denne branchen ropes `checkForInfoPopup()` før `supportTile.enabled` har forandrets. Dette vil endres senere, og da vil det være rimeligere å fjerne denne parametern.

2021-10-31 18:56 UTC, widforss commented on src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
> +        checkMap.subscription.unsubscribe();
Aner ikke. Den if-satsen er kopiert fra den gamle koden. Men sannsynligvis er det ryddig å fjerne en subscription når vi ikke vil ha en referanse til den lenger?

2021-10-31 23:43 UTC, widforss commented on src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
> +        checkMap.subscription.unsubscribe();
Men jeg skjønner ikke hvorfor vi skal ha referanser til disse subscriptions i klassevariabler en gang.

2021-11-01 08:48 UTC, widforss commented on src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
> +  checkForInfoPopup(enabled: boolean, supportTile: SupportTile = null) {
Dette er ordnet i #114.

2021-11-01 08:50 UTC, widforss commented on src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
> +        checkMap.subscription.unsubscribe();
Skjønner mer nå. Hvis man ikke unsubscribear kan det teoretisk lede til minneslekkasje.

2021-11-01 09:54 UTC, gruble requested changes
![image](https://user-images.githubusercontent.com/71138449/139654047-97204b66-488e-4a11-8ea0-f7d954d157a8.png)
Blei det litt trangt mellom disclaimer og tegnforklaringa her?

2021-11-01 10:01 UTC, widforss commented
@gruble Snarare lite mycket plats.
![legend](https://user-images.githubusercontent.com/12639272/139654933-33c634e1-9121-4e10-9528-affc022c60d2.png)

2021-11-01 10:15 UTC, gruble approved these changes
Flott!

2021-11-01 10:31 UTC, widforss commented
@gruble Såg nu att du var på #114 och testade detta. Så här ser det ut på #114 med rätt språkpack installerat
![legend2](https://user-images.githubusercontent.com/12639272/139658346-7675eb26-d4a1-4740-8c09-9de721c99088.png)
.

2021-11-01 10:32 UTC, merged