Oversettelser og syncing mot Lokalise
NVE/regObs4 pull request #115
Opened 2021-10-27 16:36 UTC by jorgkv

2021-11-01 10:49 UTC, widforss requested changes
Det er veldig store forskjeller mellom de språkfilene som er her og de som er i master i andre repot. Har du oversikt over de forskjellene?

2021-11-02 12:17 UTC, jorgkv commented
Jeg tok utgangspunkt i versjonen du sa jeg burde ta utgangspunkt i @widforss , tror det var én commit bak master. Stemmer det fortsatt?

2021-11-02 12:31 UTC, widforss approved these changes
Aner ikke hva jeg gjorde for å synes at det såg rart ut i går. Nå når jeg dobbeltsjekker ser det veldig bra ut.

2021-11-02 20:41 UTC, jorgkv commented
@widforss Det mangler en språknøkkel i sidemenyen, tittelen til steapness runout legend. Den er i siste commiten i Varsom-Regobs-Translation. Burde vi heller basert oss på den commiten her? Sjekk evt test-appen som det er linka til her 😉

2021-11-02 20:42 UTC, widforss commented
Jo, jeg trudde denne ville bli merged før mine PR:s. Derfor tenkte jeg at 1.0.185 var rimelig. Legger inn en commit her om noen minutt.

2021-11-03 08:22 UTC, merged