RO-1529: Fiks av at ruter mistet "rødmarkeringa" hvis man lukket siden og gikk inn igjen
NVE/regObs4 pull request #145
Opened 2021-12-14 18:25 UTC by gruble

Nå husker vi hvilke pakker som har feilet i tidligere nedlastingssesjon, og markerer disse i kartet når vi åpner offlinekart-oversikten.
Det var tidligere forsøk på å løse dette, men rød-markeringa ble forsøkt satt før map'en som holdt på rutene ikke var ferdig oppbygd, derfor ble ikke ruta tegnet med rød bakgrunn.
Synes det er litt vanskelig å blande RXJS med tilstand i klassen slik vi har her; fant ikke noen bedre løsning. Hadde vært stilig å hatt en Observable som sa ifra når alle features var tegnet ferdig, slik at vi kunne vente med å sette stil til denne var klar.

2021-12-15 17:30 UTC, jorgkv requested changes
Ser bra ut dette her, men gjerne fiks / tydeliggjør kommentaren, jeg forstod ikke den helt.

2021-12-15 17:30 UTC, jorgkv commented on src/app/pages/offline-map/offline-map.page.ts
> +          //we need to mark failed packages when we open modal again if packages failed in a previous session
Skjønner ikke helt kommentaren, er det når vi åpner offline.map.page igjen du mener?

2021-12-16 07:18 UTC, gruble commented on src/app/pages/offline-map/offline-map.page.ts
> +          //we need to mark failed packages when we open modal again if packages failed in a previous session
Takk. Skrev heller en kommentar ved deklarasjonen til failedPackages

2021-12-16 08:28 UTC, jorgkv approved these changes
Fint 😀

2021-12-16 08:53 UTC, merged