RO-1397: Har lagt til en knapp for å zoome inn og en for å zoome ut i kartet
NVE/regObs4 pull request #161
Opened 2022-01-24 18:03 UTC by gruble

Enkel løsning for å zoome med en finger.

2022-01-26 08:49 UTC, widforss approved these changes

2022-01-28 12:14 UTC, jorgkv requested changes
Fint dette her, har bare et bittelite endringsforslag

2022-01-28 12:14 UTC, jorgkv commented on src/app/modules/map/components/map-controls/map-zoom/map-zoom.component.scss
> +  position: initial !important;
Det er vanskelig å forstå hva position egentlig er satt til? Sett den heller til feks `relative` sånn at man skjønner hva den står som. Det er vanskelig å vite hva initial er, siden det avhenger av hva slags html-element ion-fab egentlig tilsvarer.

2022-01-28 13:22 UTC, gruble commented on src/app/modules/map/components/map-controls/map-zoom/map-zoom.component.scss
> +  position: initial !important;
Takk, har fikset det nå. Da tar jeg den inn.

2022-01-28 18:33 UTC, merged