Show snow profile plots in app
NVE/regObs4 pull request #163
Opened 2022-01-25 13:38 UTC by widforss

2022-01-25 14:10 UTC, gruble submitted a review, later dismissed
Har testet greina lokalt. Funka som fjell.

2022-01-25 14:14 UTC, gruble requested changes
Funka som fjell. Men hvordan skal vi komme oss tilbake til appen når vi er i Niviz?

2022-01-26 09:11 UTC, widforss commented on src/app/components/observation/observation-list-card/observation-list-card.component.ts
> +    const image = this.obs.Attachments[event.index] as AttachmentViewModel & {Href: string};
Det kombinerer ulike typer. Nesten, men ikke helt, som en anonym extend.

2022-01-26 10:10 UTC, gruble commented on src/app/components/observation/observation-list-card/observation-list-card.component.ts
> +    const image = this.obs.Attachments[event.index] as AttachmentViewModel & {Href: string};
Wow

2022-01-31 12:08 UTC, gruble approved these changes

2022-02-10 13:40 UTC, merged