Check ice thickness form before submission
NVE/regObs4 pull request #168
Opened 2022-01-31 17:09 UTC by widforss

2022-01-31 17:19 UTC, gruble requested changes
Det er litt vanskelig å se hva du har fikset, når mesteparten av endringene ser ut som de skyldes lint-fiks. Om du bruker en henvisning til saksnr i Jira i branch-navnet og skriver litt i PR'en om hva du har gjort, blir det litt lettere for Tante Sofie.
Nå skal jeg ikke være veldig vanskelig, jeg greier jo selv å finne Jira-saken, men tror vi sparer tid på denne måten:)

2022-01-31 17:31 UTC, gruble requested changes
Jeg får "ugyldig skjema" hvis jeg prøver å lagre istykkelse og lukke skjema uten å ha rørt "overvann før boring" eller "overvann etter boring". Er det noe jeg gjør feil?
![image](https://user-images.githubusercontent.com/71138449/151843473-ee2e5191-0e71-40f8-ab08-199a32b525eb.png)
Mulig at du har forsøkt å fikse dette, men nå får jeg en konflikt når jeg prøver å hente din siste commit:
```
C:\Repos\regobs\regObs4>git pull
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 15 (delta 13), reused 15 (delta 13), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/NVE/regObs4
 + e7b3c0fb...0990f94c fix/overvann-null -> origin/fix/overvann-null  (forced update)
Auto-merging src/app/modules/registration/pages/ice/ice-thickness/ice-thickness.page.ts
CONFLICT (content): Merge conflict in src/app/modules/registration/pages/ice/ice-thickness/ice-thickness.page.ts
Automatic merge failed; fix conflicts and then commit the result.

C:\Repos\regobs\regObs4>git status
On branch fix/overvann-null
```

2022-01-31 17:36 UTC, gruble commented
Jeg liker at du har lagt inn mulighet for å styre farge på ledeteksten på nummerfeltet!

2022-02-10 21:53 UTC, widforss commented
Tredje gången gillt. Jag har nu gått igenom koden helt och hållet, och lagt in extra variabler för att inte blanda ihop UI-värden med Reg-värden.

2022-02-11 08:40 UTC, gruble requested changes

2022-02-11 08:40 UTC, gruble commented on src/app/modules/registration/components/numeric-input/numeric-input.component.html
> +  <ion-label *ngIf="title" [color]="color" position="stacked" class="ion-text-uppercase">{{ title | translate}}
hav mener du med dette?

2022-02-11 09:53 UTC, widforss commented
Definition of done:
* Ikke gitt overvann før borring → IceHeightBefore = null
* Ja til overvann før borring → IceHeightBefore < 0
* Nei til overvann før borring → IceHeightBefor = 0
* Ikke gitt overvann etter borring → IceHeightAfter = null
* Ja til overvann etter borring → IceHeightAfter < 0
* Nei till overvann etter borring → IceHeightAfter >= 0

2022-02-11 12:34 UTC, merged