RO 1609: Fjerning av registrering(er) når vi forlater et (ugyldig) skjema
NVE/regObs4 pull request #209
Opened 2022-03-11 14:19 UTC by gruble

Forsøk på å fikse flere problemer som dukket opp hvis man hadde åpnet skjema for snøskredhendelse og lukket det igjen uten å lagre. Se https://nveprojects.atlassian.net/browse/RO-1609 for bakgrunnsinfo.
Denne PR'en har en løsning på disse punktene:
1. Jeg vet ikke om det er riktig, men mener at vi bør heller bør slette en registrering enn å nullstille den hvis vi ikke har noe data å sende inn for aktuell registrering. Dette løser problemet med obligatoriske felter i en registrering.
2. Nå sletter vi kun bilder som hører til registreringen(e) i skjemaet
3. Har forenklet måten å overstyre hvordan man nullstiller eller sletter data i et skjema

Dette er ikke på plass og her trenger jeg litt hjelp:
- [ ] Å validere at overstyring av nullstilling av skjema virker. Har en test på dette, men denne feiler fordi jeg ikke vet hvordan jeg skal sjekke at en AvalancheObs er tom.

2022-03-14 14:13 UTC, jorgkv requested changes
Har noen spørsmål og kommetarer. Burde vi slå sammen base.page og base.page.service? Jeg ser ikke helt nytten av å ha disse separat lenger, særlig hvis vi flytter noe av funksjonaliteten til draft.repository.service og registration.helpers

2022-03-14 14:13 UTC, jorgkv commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.ts
> +  protected async doReset() {
Hvorfor trenger vi både reset og delete? Skulle tro at en av dem holder.

2022-03-14 14:13 UTC, jorgkv commented on src/app/modules/registration/pages/base-page-service.ts
> +  async reset(draft: RegistrationDraft, registrationTids: RegistrationTid[], doDelete = false) {
Denne burde kanskje ligge på draft repository service

2022-03-14 14:13 UTC, jorgkv commented on src/app/modules/registration/pages/base.page.ts
> +        return false; //operator wants to stay
Skjønte ikke hva du mente først her, med denne kommentaren. Er ikke "user" god nok beskrivelse av brukeren? Eller er det noe jeg ikke skjønner helt likevel?

2022-03-14 14:13 UTC, jorgkv commented on src/app/modules/registration/pages/base-page-service.ts
>    createDefaultProps(draft: RegistrationDraft, registrationTid: RegistrationTid): RegistrationDraft {
Denne og getDefaultValue tenker jeg kan flyttes ut av servicen, inn i registration.helpers-fila.

2022-03-14 14:13 UTC, jorgkv commented on src/app/modules/registration/pages/base-page.service.spec.ts
> +    expectedEmptyDraft['AvalancheObs'] = {};
Her er det noe muffens, mener du eventuelt `expectedEmptyDraft.registration['AvalancheObs']`? men jeg tenker at testen er feil, hvis vi resetter så vil vi vel egentlig at verdien er helt fjernet - eller?

2022-03-14 14:22 UTC, gruble commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.ts
> +  protected async doReset() {
Godt spørsmål. I såfall burde vi fjerne reset, synes jeg.
Ser ikke helt nytten av å "tømme" et objekt, med mindre objektet må initialiseres med noen spesielle data.
Initialisering med standard-verdier kan vi sikkert løse direkte i de skjemaene som måtte trenge dette.

2022-03-14 14:24 UTC, gruble commented on src/app/modules/registration/pages/base.page.ts
> +        return false; //operator wants to stay
Kan gjerne bytte fra "operator" til "user"

2022-03-14 14:29 UTC, gruble commented on src/app/modules/registration/pages/base-page.service.spec.ts
> +    expectedEmptyDraft['AvalancheObs'] = {};
Det er feil i koden, ja. Endrer til expectedEmptyDraft.registration['AvalancheObs']. Takk!
Men hvis vi alltid sletter skjemaet når vi gjør reset, så er denne testen ikke relevant lengre.

2022-03-14 14:31 UTC, gruble commented
> Har noen spørsmål og kommetarer. Burde vi slå sammen base.page og base.page.service? Jeg ser ikke helt nytten av å ha disse separat lenger, særlig hvis vi flytter noe av funksjonaliteten til draft.repository.service og registration.helpers

Jeg er helt for å kutte ut base.page.service. Blei litt kunstig skille mellom base.page og base.page.service.

2022-03-17 16:37 UTC, gruble commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.ts
> +  protected async doReset() {
Har fjernet doReset nå

2022-03-17 16:38 UTC, gruble commented on src/app/modules/registration/pages/base-page-service.ts
> +  async reset(draft: RegistrationDraft, registrationTids: RegistrationTid[], doDelete = false) {
Beholder den der den er. Å fjerne base-page.service blei bare styr.

2022-03-24 09:06 UTC, merged