RO-1695: Nå får vi med oss at alle skjema er endret i skjemaoversikten
NVE/regObs4 pull request #241
Opened 2022-04-20 13:44 UTC by gruble

Nå kjører vi en deepEquals på alle skjema for å fange opp endringer. Sikkert ikke nødvendig i og med at vi bare viser data fra enkelte skjemaer i oversikten, men da slipper vi å spesialbehandle enkeltskjema seinere.

2022-04-20 14:07 UTC, jorgkv commented
Jeg vil gjerne kikke på denne før den merges inn.

2022-04-21 07:55 UTC, widforss requested changes
Har lest litt mer kode nå på morgenen.

Er det ikke mer lurt å sjekke om `.summaryItems$` har blitt forandret, siden vi der har et (1) enhetlig grensesnitt og et begrenset antall attributt som skal renderes?

2022-04-21 13:43 UTC, jorgkv requested changes
Jeg syns dette ser bra ut 👍  Har bare noen små forslag til endringer.

2022-04-21 13:43 UTC, jorgkv commented on src/app/modules/registration/services/summary-item.service.spec.ts
> +  beforeEach(() => TestBed.configureTestingModule({}));
Denne kan tas bort.

2022-04-21 13:43 UTC, jorgkv commented on src/app/modules/registration/services/summary-item.service.spec.ts
> +  it('draftHasNotChanged should detect changes in comment schema', async () => {
Denne trenger ikke være async

2022-04-21 13:43 UTC, jorgkv commented on src/app/modules/registration/services/summary-item.service.ts
> +  for (const tid of allTidsThatMayHaveChanged) {
Holder det ikke her å bare sjekke `curTids`? Mulig det er noen tilfeller jeg ikke ser helt, legg gjerne til en kommentar som forklarer hvorfor vi trenger å sjekke også `preTids` i så fall?

2022-04-21 13:52 UTC, jorgkv commented
> Er det ikke mer lurt å sjekke om `.summaryItems$` har blitt forandret, siden vi der har et (1) enhetlig grensesnitt og et begrenset antall attributt som skal renderes?

Det kunne vi også gjort, vi kan godt endre til det for min del. Jeg lagde det slik opprinnelig for å slippe å hente attachments så ofte, men når vi uansett nå bruker `combineLatest` på attachments og gjenbruker de videre så er ikke det så viktig lenger. 
Ved å ha "endret-sjekken" så tidlig som mulig slipper vi å kjøre koden for å generere summaries, som blant annet gjør noen async kall for å oversette tekst, men det er ikke sikkert det gjør så mye.

2022-04-21 13:55 UTC, jorgkv commented
Feilen gjaldt forøvrig alle "hoved-kommentarer" (på alle skjema), ikke bare i selve kommentar-skjemaet. Jeg hadde ikke fått med meg at alle kommentarer ble vist i oversikten.

2022-04-21 14:30 UTC, gruble commented on src/app/modules/registration/services/summary-item.service.spec.ts
> +  beforeEach(() => TestBed.configureTestingModule({}));
Det er sant. Fikset nå.

2022-04-21 14:30 UTC, gruble commented on src/app/modules/registration/services/summary-item.service.spec.ts
> +  it('draftHasNotChanged should detect changes in comment schema', async () => {
Stemmer!

2022-04-21 14:32 UTC, gruble commented on src/app/modules/registration/services/summary-item.service.ts
> +  for (const tid of allTidsThatMayHaveChanged) {
Jo, det tror jeg er riktig. Jeg lurte på om den kom til å fange opp hvis vi f.eks. slettet et skjema og la til et annet, slik at antall skjema var likt. La til et par tester for å sjekke, men virker som den forenklede logikken holder.

2022-04-21 14:35 UTC, gruble commented
> > Er det ikke mer lurt å sjekke om `.summaryItems$` har blitt forandret, siden vi der har et (1) enhetlig grensesnitt og et begrenset antall attributt som skal renderes?
> 
> Det kunne vi også gjort, vi kan godt endre til det for min del. Jeg lagde det slik opprinnelig for å slippe å hente attachments så ofte, men når vi uansett nå bruker `combineLatest` på attachments og gjenbruker de videre så er ikke det så viktig lenger. Ved å ha "endret-sjekken" så tidlig som mulig slipper vi å kjøre koden for å generere summaries, som blant annet gjør noen async kall for å oversette tekst, men det er ikke sikkert det gjør så mye.

Dette har jeg ingen sterke meninger om. Synes det er greit nå, men hvis dette forenkler mye, er det kanskje verdt det?
Jeg gjør ikke noe mer med denne nå før vi har blitt enige i hvert fall:)

2022-04-21 14:43 UTC, jorgkv approved these changes
Bra greier. Å bare sjekke med deepEquals på summaries forenkler nok koden en del, men er kanskje noen ms tregere og litt vanskeligere å teste. For min del kan du også bare merge den inn nå.

2022-04-21 14:47 UTC, merged