Fixes offline fallback for overview page
NVE/regObs4 pull request #242
Opened 2022-04-21 13:07 UTC by widforss

Also phases out the <app-offline-image> component, since
the <app-remote-image> accomplishes the same thing.

2022-04-22 06:44 UTC, gruble reviewed
Når jeg klikker på erstatningsbildet når jeg ikke har nett, får jeg svart skjerm. Mulig det er greit altså, jeg bare lurte på om det var lett å fikse?

2022-04-22 07:15 UTC, gruble requested changes
Dette funka veldig bra! 
Bra at du har fått brukt samme komponent til alt av bildevisning.
Jeg har bare noen få kommentarer jeg ønsker at du ser på.
Vannstands-bilder fungerer også.

2022-04-22 07:15 UTC, gruble commented on src/app/modules/shared/components/remote-image/remote-image.component.ts
> +    console.log(this)
Bruk LoggingService i stedet om du trenger å logge noe her

2022-04-22 07:15 UTC, gruble commented on src/app/modules/shared/components/remote-image/remote-image.component.html
>      <ion-icon name="image"></ion-icon>
Denne teksten må oversettes. Du kan også gjøre noen små-justeringer for å få korrekt norsk tekst. Det skal være "å" mellom "ikke" og "laste". Og det mangler et punktum på slutten av linja.

2022-04-22 07:15 UTC, gruble commented on src/app/modules/shared/components/remote-image/remote-image.component.ts
>  export class RemoteImageComponent implements OnInit {
Kan du spandere litt dokumentasjon her?
Hva er ansvarsområdet til denne komponenten? Hva kan den gjøre?

2022-04-22 07:39 UTC, widforss commented on src/app/modules/shared/components/remote-image/remote-image.component.ts
> +    console.log(this)
Oi, den skal ikke være der ...

2022-04-25 08:21 UTC, gruble approved these changes
Bra jobba!

2022-04-25 08:50 UTC, merged