Combine pages for obs location and datetime
NVE/regObs4 pull request #254
Opened 2022-05-24 07:09 UTC by widforss

2022-05-25 09:14 UTC, gruble requested changes
Fungerte utmerket.
Har noen kommentarer som går på struktur/lesbarhet.
Lintern min klager også over manglende semikolon og feil innrykk, så fint om du tar det også!

2022-05-25 09:14 UTC, gruble commented on src/assets/i18n/nn.json
> +      "CONFIRM_TEXT": "Stadfest observasjonspunkt og -tid",
Tror korrekt norsk er uten bindestrek foran "tid". Gjelder alle steder hvor det står "Observasjonspunkt og -tid"

2022-05-25 09:14 UTC, gruble commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
> +  @Output() locationTimeSet = new EventEmitter<[ObsLocationEditModel, string]>();
I stedet for å sende ObsLocationEditModel og string, du skulle ikke lage et interface som inneholder begge disse variablene?
Tror det hadde gjort det lettere å forstå koden fordi da får observasjonstiden et variabelnavn. Enda tydeligere hadde blitt om tiden hadde typen Date. 
Jeg skjønner at modellen vil ha tidspunktet formatert som tekst, men kanskje vi kan overlate konverteringa til den komponenten som lagrer tidspunktet i modellen?

2022-05-25 09:14 UTC, gruble commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
> +  @Input() localDate: string;
Se kommentar over om å bruke Date i stedet for string

2022-05-25 10:19 UTC, widforss commented on src/app/modules/registration/pages/obs-location/obs-location.page.ts
> +  private async setLocationTimeAndSaveDraft([loc, time]: [ObsLocationEditModel, string]) {
@gruble Kan godt endre type til Moment, men jeg skjønner ikke behovet for et interface, da jeg destrukturerer arrayen til to variabler der det kreves.

2022-05-25 10:27 UTC, gruble commented on src/app/modules/registration/pages/obs-location/obs-location.page.ts
> +  private async setLocationTimeAndSaveDraft([loc, time]: [ObsLocationEditModel, string]) {
Akkurat på den linja du har kommentert gir det kanskje ikke så mye mening, selv om jeg mener at også her blir koden enklere ved å bruke et interface. Men hvis du ser der output-eventet er deklarert på linje 60, så mener jeg bestemt at det ville bli lettere å forså hva komponenten sender om du bruker et interface. Skal du bruke dette eventet må du se på der eventet bygges opp for å forstå hva string-variabelen er til:
`@Output() locationTimeSet = new EventEmitter<[ObsLocationEditModel, string]>()Jeg mener det blir lettere å forså hva `

2022-05-25 12:04 UTC, widforss commented on src/assets/i18n/nn.json
> +      "CONFIRM_TEXT": "Stadfest observasjonspunkt og -tid",
Er ikke dette eksakt samme situasjon som i "Norges vassdrags- og energidirektorat"?

2022-05-25 12:33 UTC, gruble commented on src/assets/i18n/nn.json
> +      "CONFIRM_TEXT": "Stadfest observasjonspunkt og -tid",
Laila var helt enig med deg:)

2022-05-25 12:33 UTC, gruble commented on src/assets/i18n/nn.json
> +      "CONFIRM_TEXT": "Stadfest observasjonspunkt og -tid",
Bra det er noen som kan norsk i Regobs-prosjektet;-)

2022-05-31 07:45 UTC, widforss commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
> +  @Input() localDate: string;
Jeg har sett på dette nå. Vi kan endre til `Moment` eller `Date`, men `ion-datetime` krever at kobles til en `string`, ellers fungerer ikke det elementet. Så om vi gjør sånn må vi ha dobbel representasjon for datoene, en `string` og en `Date`/`Moment`. Du får gjerne fundere på hva som blir minst dårlig under uken.

2022-06-01 07:40 UTC, gruble commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
> +  @Input() localDate: string;
Har lest dokumenasjonen til ion-datetime og skjønner det ligger en tanke bak. Så da legger jeg meg flat:)
Dobbelt opp med variable er ingen god løsning synes jeg.

2022-06-01 09:58 UTC, widforss commented on src/app/modules/registration/pages/obs-location/obs-location.page.ts
> +  private async setLocationTimeAndSaveDraft([loc, time]: [ObsLocationEditModel, string]) {
Da lager jeg et interface for dette, og så er det ferdig kodemessig. Må få ok fra Atle også, kan du purre på han under uken?

2022-06-01 10:06 UTC, gruble commented on src/app/modules/registration/pages/obs-location/obs-location.page.ts
> +  private async setLocationTimeAndSaveDraft([loc, time]: [ObsLocationEditModel, string]) {
Supert! Jeg ber Atle teste PR-bygget

2022-06-07 22:56 UTC, widforss commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
> +  @Output() locationTimeSet = new EventEmitter<[ObsLocationEditModel, string]>();
Interface er laget nå.

2022-06-08 06:11 UTC, gruble approved these changes
Lekkert!

2022-06-08 06:52 UTC, merged