Uses new SubPage redirect to get to account subpage
NVE/regObs4 pull request #273
Opened 2022-07-27 15:04 UTC by widforss

2022-08-11 10:04 UTC, gruble requested changes
Jeg har rullet ut redirect-funksjonen i B2C til test nå.
Når jeg tester å trykke på "slett-meg-knappen", åpnes denne url'en:
https://test-konto.nve.no/User?Culture=nb-NO&tag=user-data#user-data
og jeg får denne feilmeldinga:
Error.
An error occurred while processing your request.
Request ID: |be904cd6-4b62fcf13a30223c.

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.

2022-08-11 11:03 UTC, gruble requested changes
Jeg har testet forskjellige versjoner av NVE-konto:
20220809.1 funker ikke
20220117.3 funker ikke
20220117.2 funker ikke
20211013.1 funker ikke
20210507.1 funker
Har derfor rullet helt tilbake til 20210507.1
Tipper feilen skyldes endringer som skjedde i TFS mellom 20210507.1 og 20211013.1.

2022-09-15 08:55 UTC, gruble requested changes
Når jeg kjører denne greina mot test eller demo, kommer jeg fortsatt bare til "Brukerinformasjon" i NVE-konto når jeg trykker på "Slett profil og mine data" i Regobs-appen på iOS.
Men det virker som B2C i hvert fall fungerer med det bygget du har kjørt ut, og det er bra!

2022-09-15 10:31 UTC, widforss commented
Hva er forskjellen mellom oppsettene våre, @gruble? Fordi her fungerer det fint

https://user-images.githubusercontent.com/12639272/190381790-13843988-77c6-4c22-b580-8502bf081321.mp4

2022-09-15 10:32 UTC, widforss commented
jaha, ios

2022-09-15 11:19 UTC, gruble approved these changes
Bra jobba!
Jeg har altså da testet uten den siste commit'en, så den kan du bare ta vekk.

2022-09-15 11:49 UTC, merged