add location marker and PictureMarkerSymbol for GeoHazards
NVE/regObs4 pull request #30
Opened 2021-05-04 10:55 UTC by nicolaimich

2021-05-04 11:06 UTC, gruble commented
Dette tenkte vi sikkert ikke på, men jeg tror vi må løse det: Markøren må nok 
flyttes slik at det er spissen av markøren som "peker på" lokasjonen. Se vedlagte sammenligning mellom gammel og ny løsning.
![marker-posiion](https://user-images.githubusercontent.com/71138449/116994846-8f7ac300-acd9-11eb-9107-1055b367c658.PNG)

2021-05-04 11:11 UTC, nicolaimich commented
Bra sett. Det kan nok løses med yoffset til PictureMarkerSymbol tipper jeg.

2021-05-04 14:07 UTC, gruble requested changes

2021-05-04 14:07 UTC, gruble commented on src/app/modules/map/core/classes/regobs-geohazard-marker.ts
> +export class RegobsGeoHazardMarker {
Her er det mye kode som ikke blir brukt. Trenger dette å være en egen klasse lengre eller kunne man like gjerne flytta de to funksjonene som brukes inn i MapItemMarker?

2021-05-04 14:07 UTC, gruble commented on src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
>        //TODO: Få SVG-til å virke! symbol: new SimpleMarkerSymbol({ path: symbolPath })
Den TODO'en har du vel fiksa?-)

2021-05-06 11:29 UTC, nicolaimich commented
- Added 4 SVG icons for outline
- Removed RegobsGeoHazardMarker class. Place two of the functions inside map-item-marker
- Add yoffset and TODO comments

2021-05-06 11:44 UTC, merged