Bugfix/ro 1318/email open error handling
NVE/regObs4 pull request #323
Opened 2022-09-27 11:51 UTC by amish1188

Web app: Nå vil både 'Reporter feil' og 'Kontakt oss' knapp åpne kontakt skjema som var allerede i bruk på regobs.no
App: Gjelder hovedsakelig iphone brukere, hvis man ikke har Mail appen så får man toast med beskjed.
Har strukturert kode litt.

2022-09-27 13:50 UTC, gruble requested changes
Det virker som du har del formateringsfeil i denne PR. Sjekk oppsett av linting hos deg!
Jeg har ikke testet på tlf ennå. Tenkte jeg kunne vente til du har fikset de småtingene jeg har påpekt.

2022-09-27 13:50 UTC, gruble commented on src/app/modules/shared/services/email-composer/email-composer.service.ts
> +    private translateService: TranslateService) {}
Har du sjekket linting for denne fila? Det ble litt trangt her;)

2022-09-27 13:50 UTC, gruble commented on src/app/modules/shared/services/logging/file-logging.service.ts
> +      if(canSend){
Sjekk forrige kommentar om linting

2022-09-27 13:50 UTC, gruble commented on src/app/modules/shared/services/logging/file-logging.service.ts
> +
Du trenger kanskje ikke filene før du vet om du kan sende epost?

2022-09-27 13:50 UTC, gruble commented on src/app/modules/side-menu/components/side-menu.component.ts
> +    if(Capacitor.isNativePlatform()){
linting..

2022-09-27 13:50 UTC, gruble commented on src/app/modules/side-menu/components/side-menu.component.ts
> +    let optional;
Hva inneholder denne variabelen? Kan du finne på et mer presist navn?

2022-09-27 13:50 UTC, gruble commented on src/assets/i18n/nb.json
> +    "NO_EMAIL_APP": "Epost kan ikke sendes. Hvis du er Iphone bruker du må ha Mail app til å sende eposter direkte fra Regobs appen.",
Kan vi gjøre det lettere for bruker å forstå hva som er feil og hvordan de kan fikse det?
Det mangler også en forklaring på hva som er feil (årsak) for Android-brukere.
Her er nytt forslag:
_Epost kan ikke sendes, fordi vi ikke får kontakt med epost-appen på telefonen. På iPhone må du ha appen "Mail"._
(har ikke oversatt til engelsk, det gjør du sikkert mye bedre enn meg:)

2022-09-29 14:04 UTC, jorgkv approved these changes
Bra jobba!

2022-09-29 14:09 UTC, gruble approved these changes

2022-09-29 14:10 UTC, merged