Endre skjema for ulykke / hendelse for snø og is
NVE/regObs4 pull request #342
Opened 2022-10-24 08:18 UTC by robinzaal

Oppdatert med nye felter fra API

2022-10-24 08:24 UTC, robinzaal commented on src/app/modules/registration/pages/dirt/landslide-obs/landslide-obs.page.html
> +      <!--  <app-kdv-select title='REGISTRATION.DIRT.LAND_SLIDE_OBS.DAMAGE_EXTENT' kdvKey='DamageExtentKDV'
Mye linting-tull her, men har egentlig kun kommentert ut denne kdv-select'en.

2022-10-24 09:32 UTC, widforss requested changes

2022-10-24 09:32 UTC, widforss commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.html
> +      <app-numeric-input title="REGISTRATION.SNOW.AVALANCHE_OBS.HARMED_NUM"
Skal denne virkelig være her og ikke under ulykke?

2022-10-24 09:32 UTC, widforss commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.html
> +      <app-kdv-select title="REGISTRATION.SNOW.AVALANCHE_OBS.LOCAL_TOURIST_TID" kdvKey="LocalTouristKDV"
Dito, tror dette bør være under ulykke

2022-10-24 09:32 UTC, widforss commented on src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.html
> +      <app-kdv-select title="REGISTRATION.SNOW.AVALANCHE_OBS.LOCAL_KNOWLEDGE_TID" kdvKey="LocalKnowledgeKDV"
Skal være under ulykke.

2022-10-24 09:32 UTC, widforss commented on src/app/components/incident/incident.component.html
> +    {{'REGISTRATION.CHECK_TO_ANONYMIZE' | translate}}
Spørs om dette skal gjøres ekstra tydelig. Emma hadde tidligere en idé om at man kunde sette denne rett fra +-menyen på kartet. Den gjører ikke noe nytte hvis folk ikke skjønner veldig tydelig at alternativet finnes der.

2022-10-24 10:35 UTC, jorgkv commented
Husk å ta en search-replace på alle `eslint` / `tslint`-endringene i modellene etter at de ble generert på nytt. Vi bruker ikke tslint i prosjektet, men swagger-generatoren legger til tslint default.

2022-10-24 11:54 UTC, widforss commented
Is melder at det ikke er ønskelig å kunne sende inn anonyme  isobservasjoner.

2022-10-25 11:28 UTC, robinzaal commented
> Husk å ta en search-replace på alle `eslint` / `tslint`-endringene i modellene etter at de ble generert på nytt. Vi bruker ikke tslint i prosjektet, men swagger-generatoren legger til tslint default.

Jeg la til en [.eslintignore-fil](https://github.com/NVE/regObs4/blob/0cfc78666565830b033d976179fe4403dbc454f9/.eslintignore) slik at vi kan ignorere de eslint/tslint kommentarene fremover.

2022-10-27 10:33 UTC, merged

2022-10-27 19:06 UTC, widforss commented
@robinzaal
1. Bør ikke incident.EvacuatedNum, incident.MaterialDamages og incident.SlopeActivityTID være under Incident? Hvis ikke, hvorfor er de i incident-skjemaet i API:et i stedet for AvalancheObs-skjemaet?
2. Det er ikke ryddig å legge ting inn rett under headern her når alt annet koblet til Incident er i en egen modul. Disse feltene bør legges inn i app-incident-component.

2022-10-27 19:19 UTC, widforss commented
I fremtiden kan det også være en god idé å squashe en sånn her PR når du merger, så blir historikken i develop tydligere.