Add new PST and RB snow tests
NVE/regObs4 pull request #350
Opened 2022-11-02 18:35 UTC by widforss

2022-11-03 10:58 UTC, gruble requested changes
Ser ut som det virker bra. Jeg legger ved et skjermutklipp fra da jeg skulle redigere testene etter at jeg sendte dem inn. Da står det "Ikke spesifisert" på alle sammen. Vet ikke hva dette er:
![image](https://user-images.githubusercontent.com/71138449/199703888-ec881e1d-aad3-41cc-9a10-c2682c7fdac0.png)

2022-11-03 10:58 UTC, gruble commented on src/app/modules/common-regobs-api/regobs-api-configuration.ts
> +  rootUrl: string = 'http://localhost:40001';
Hva brukes denne til og hvorfor endrer du den?

2022-11-03 10:58 UTC, gruble commented on src/assets/i18n/nb.json
> +        "RB_RELEASE": "Løsnet del av blokk",
Ta med % ?

2022-11-03 11:23 UTC, gruble requested changes, later dismissed
Legger du ved nynorsk tekst også så blir Jostein glad:)
![image](https://user-images.githubusercontent.com/71138449/199708597-4602e042-45eb-4dbc-992f-8ac5fab14f46.png)

2022-11-03 14:24 UTC, widforss commented on src/app/modules/common-regobs-api/regobs-api-configuration.ts
> +  rootUrl: string = 'http://localhost:40001';
Jeg aner ikke hvorfor den er endret eller hvorfor det er sjekket inn, eller hva den gjør.

2022-11-04 08:48 UTC, widforss commented
> Ser ut som det virker bra. Jeg legger ved et skjermutklipp fra da jeg skulle redigere testene etter at jeg sendte dem inn. Da står det "Ikke spesifisert" på alle sammen. Vet ikke hva dette er: ![image](https://user-images.githubusercontent.com/71138449/199703888-ec881e1d-aad3-41cc-9a10-c2682c7fdac0.png)

Skal sies at dette var Fracture type som ikke hadde en *ngIf, og det er nå addressert.

2022-11-04 09:30 UTC, jorgkv approved these changes
Bra 👍

2022-11-04 09:32 UTC, merged