Implementere gjenbrukbar modal service for "ja/nei"-modaler.
NVE/regObs4 pull request #358
Opened 2022-11-10 14:34 UTC by robinzaal

I dag er det samme implementasjon forskjellige plasser i appen, som alle bruker så og si samme kode. Denne PR-en har som mål å samle disse og bruke samme service alle steder. 

Dette vil også fjerne en bug hvor bruker godtar "hendelsen" ved å trykke på utsiden av modalvinduet (på det såkalte "backdrop")

En viktig endring her er at vi nå setter `backdropDismiss` til `false` [her](https://github.com/NVE/regObs4/blob/0ed70dc7f3c2b433bf4974e5c642a0dc58faab97/src/app/core/services/confirmation-modal/confirmation-modal.service.ts#L73), som vil si at brukeren ikke kan klikke seg ut av modalen og dermed må ta et valg med knappene.

2022-11-10 18:00 UTC, jorgkv commented
Fin beskrivelse 👍

2022-11-11 10:23 UTC, gruble requested changes
Synes dette så veldig lovende ut. Ryddig kode.
Digg at du rydder opp i dette slik at vi får fjernet masse unødvendig kode og gjør det likt og skikkelig over alt.
Dialogboksene så også fine ut på web. Har ikke testet på mobil.
Har noen kommentarer og forslag.

2022-11-11 10:23 UTC, gruble commented on src/app/core/services/confirmation-modal/confirmation-modal.service.ts
> +   * @param opts
Hadde vært supert med litt forklaring på hver parameter her. Og er det riktigere å kalle det messageKey og headerKey siden dette egentlig er en nøkler til tekster i språkfila og ikke tekst i seg selv?

2022-11-11 10:23 UTC, gruble commented on src/app/core/services/confirmation-modal/confirmation-modal.service.ts
> +   * @returns Promise boolean value based on user button input.
Dokumentere hva som gjør at man får false eller true, altså koblingen mellom knappens "role" og hva metoden returnerer?

2022-11-11 10:23 UTC, gruble commented on src/app/modules/registration/components/send-button/send-button.component.ts
> +            text: translations['DIALOGS.NO'],
Hadde vært digg om vi kunne sende inn nøkkel til språkfila i stedet for teksten på knapper, akkurat slik vi gjør for message og header. Da hadde vi sluppet å hente tekstene fra språkfila her og heller overlatt det til popup'en.

2022-11-11 10:23 UTC, gruble commented on src/app/modules/registration/components/send-button/send-button.component.ts
>          'DIALOGS.YES',
Tekstene for header og message trenger vi kanskje ikke å laste her?

2022-11-11 10:23 UTC, gruble commented on src/app/core/services/confirmation-modal/confirmation-modal.service.ts
> +   *
Hadde vært fint om det sto litt her om hva som var "default-knapper" og oppførsel

2022-11-11 10:23 UTC, gruble commented on src/app/modules/registration/pages/save-as-draft.guard.ts
> +            {
Denne trenger et tredje valg, avbryt, hvis det er teknisk mulig å avbryte operasjonen og gå tilbake. Jeg synes det er litt skummelt å bruke avbryt-valget til å forkaste kladden. 
Testet på web nå, og hvis vi hadde hatt et avbryt-valg som avbrøt operasjonen kunne vi også støttet at man trykket på ESC-knappen på tastaturet.

2022-11-11 10:23 UTC, gruble commented on src/app/modules/registration/components/send-button/send-button.component.ts
> +            role: PopupResponse.CANCEL
Her burde knappen som har rollen CANCEL kunne aktiveres ved å trykke på ESC-knappen på web

2022-11-11 13:30 UTC, gruble commented on src/app/modules/registration/pages/save-as-draft.guard.ts
> +            {
ESC-knapp-støtte er mindre viktig enn å ha et separat avbryt-valg som stopper navigering vekk fra registrering.

2022-11-11 14:30 UTC, amish1188 commented
ser veldig bra ut! kanskje vi kan også ha noe hover effekt på knappene på weben?

2022-11-15 10:23 UTC, gruble approved these changes

2022-11-15 11:26 UTC, merged