sort by date
NVE/regObs4 pull request #376
Opened 2022-11-25 13:16 UTC by amish1188

Added sort by date in a list view. Url should be orderBy=changeTime or obsTime
Updated skeleton view of the list also.

2022-11-28 11:48 UTC, gruble requested changes
Det ser lovende ut, det her.
Jeg har noen kommentarer.
Det så også ut som høyre kant av dropdown er ikke på linje med høyre kant av osbervasjonskortene.
Har du kjørt lint før du sjekket inn? Det virker litt tilfeldig om du bruker mellomrom i funksjonshoder eller ikke.

2022-11-28 11:48 UTC, gruble commented on src/assets/i18n/en.json
> +    "OBSERVATIONS": "Observations",
Oversetterne må skjønne hva denne teksten brukes til. Kan du bruke en nøkkel som beskriver dette bedre?

2022-11-28 11:48 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  setOrderBy(order: string){
Hvilke verdier kan man sende inn? Kan du begrense typen? Dokumentere?

2022-11-28 11:48 UTC, gruble commented on src/assets/i18n/nb.json
> +    "SORT_BY_TEXT": "Sortert på",
Sorter på

2022-11-28 11:48 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +    const orderBy = this.activatedRoute.snapshot.queryParams['orderBy'];
Jeg tror det er bedre å lytte på endringer i SearchCriteriaService.searchCriteria$ enn å lese fra URL her. Det kan funke å lese fra URL og men det er SearchCriteriaService som bestemmer hva URL-parametrene og verdiene skal være.
Her hardkoder du. OnceAndOnlyOnce!-)

2022-11-28 11:48 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +    this.popupType = Capacitor.isNativePlatform() ? 'action-sheet' : 'popover';
Hvorfor er denne linja akkurat her? Linja over og under hører sammen, synes jeg.

2022-11-28 11:48 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +function  convertToShorterName(value: string): string{
Denne funksjonen og funksjonen readOrderBy() gjør egentlig det samme, bare motsatt. Dette kan du gjøre mer ryddig ved å sette opp en Map mellom url-verdi og verdien som skal sendes til API, slik at du slipper å hardkode mer enn ett sted. Navnet "convertToShorterName" sier meg ingenting. Greier du å velge et funksjonsnavn som sier noe om hva denne skal brukes til?

2022-11-28 11:48 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  private readOrderBy(orderBy: string){
orderBy kan ikke være en hvilken som helst tekst. Kan du begrense hvilke valg man har?

2022-11-28 13:17 UTC, amish1188 commented on src/assets/i18n/nb.json
> +    "SORT_BY_TEXT": "Sortert på",
endret til TITLE

2022-11-30 07:52 UTC, gruble requested changes
Kommer seg. Dette blir bra til slutt;-)

2022-11-30 07:52 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  // [changeTime, DtChangeTime] [obsTime, DtObsTime]
Hva er dette til?

2022-11-30 07:52 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
>    private readOrderBy(orderBy: string){
Hvilken type returnerer denne?

2022-11-30 07:52 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    if (orderBy in ORDER_BY_TYPE) return UrlDtoOrderByMap.get(orderBy);
Map.get() vil returnere null tror jeg om den ikke finner nøkkelen, så du trenger ikke sjekke først om nøkkelen er der

2022-11-30 07:52 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +'changeTime', 'obsTime' , 'DtObsTime' , 'DtChangeTime'
Jeg lurer på om du ville være mer tjent med å splitte denne i to, en for lovlige url-parametre og en for lovlige sorteringsvalg i søkekriteria. Da unngår du at utvikler roter med hvilken hun skal bruke. Jeg tror også koden din ville bli enklere om du brukte typer i stedet for enum, f.eks.:
`type SearchCriteriaOrderBy = 'DtObsTime' | 'DtChangeTime';`

2022-11-30 07:52 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    if (order in ORDER_BY_TYPE) this.searchCriteriaChanges.next({ OrderBy: order });
Dette ville blitt enklere og sikrere om order var en type og ikke en enum. Da ville du fått kompileringsfeil om du forsøkte å sende inn noe annet enn det som er relevant. Nå skjer det ingenting.

2022-11-30 07:52 UTC, gruble commented on src/app/components/observation/observation-skeleton/observation-skeleton.component.scss
> +                                ion-col {
Litt raus med innrykket her eller?-) Gjelder flere steder i css

2022-11-30 16:04 UTC, gruble approved these changes

2022-12-01 07:59 UTC, gruble requested changes
Fant en feil når jeg testet PR-bygget nå:

[ERROR][UnhandledException] Unhandled exception occurred in app.
console-logging.service.ts:54 TypeError: Cannot read properties of undefined (reading '0')
    at convertApiOrderByToUrl (search-criteria.service.ts:48:20)
    at SearchCriteriaService.setUrlParams (search-criteria.service.ts:204:36)

![image](https://user-images.githubusercontent.com/71138449/204997758-a60eb3f3-9cba-4718-b92b-3e87fcaf18b1.png)

2022-12-02 11:16 UTC, gruble approved these changes

2022-12-02 11:16 UTC, gruble commented on src/assets/i18n/nb.json
>    },
Jeg vet du bare har valgt tekster som sto i Jira-oppgaven, men jeg tror det er bedre å skrive enten
1) Sorter på:  Observert tid / Oppdatert tid
eller
2) Sortering: Sist observert / Sist oppdatert

2022-12-02 11:17 UTC, merged