RO-2070: Fått opp farten på søk etter observasjoner
NVE/regObs4 pull request #377
Opened 2022-11-28 09:27 UTC by gruble

Det viste seg at appen fortsatt prøvde å hente observasjoner data til offline-bruk selv på web.
I tillegg til at-a-glance-søk ble ObservationService.updateObservations() kjørt hver gang man utvidet tidsrommet for observasjoner. Denne trigget fullt søk og kræsjet indexedDB når det returnerte, antakelig pga. for mye data.

Har også gjort et lite stunt på oppfrisk-knapp og visning av sist-oppdatert-tidspunkt i filter-menyen. Trenger å diskutere løsning for dette, er ikke helt fornøyd så langt.

2022-12-14 11:52 UTC, jorgkv commented
Setter denne til draft siden den har endringer i en annen PR som evt skal inn først osv.

2022-12-19 12:15 UTC, jorgkv requested changes
Har sett gjennom deler av endringene, ser på resten når du har sett på kommentarene.

2022-12-19 12:15 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +export function withinExtentCriteriaToBounds(extent: WithinExtentCriteriaDto): L.LatLngBounds {
Hvorfor ligger disse funksjonene her, hvis de ikke brukes i servicen?

2022-12-19 12:15 UTC, jorgkv commented on src/app/core/services/search-registration/search-registration.service.ts
> +  private lastFetched = new Subject<Date>();
Jeg tror ikke denne servicen bør holde styr på når det sist ble søkt osv. lastFetched gir bare mening sammen med hvilke søkekriterer som ble brukt. lastFetched for kartvisningen vil alltid være noe annet enn for listevisningen og mine observasjoner, siden andre søkekriterier / andre søkemetoder har blitt brukt.

Vi kan også risikere at man ser på observasjoner i kartet og lastFetched er oppdatert, men så går man til listevisninga, men da har man mista nett og får ikke søkt. Da vil det stå en sist oppdatert dato selv om man ikke får sett på observasjoner, som vil virke rart for brukerne tror jeg? 

Tror derfor hver enkelt side der det søkes, kartsiden, listevisningen, mine observasjoner (hvis det er aktuelt der også), selv må holde styr på dette. Akkurat hvordan vi skal løse det vet jeg ikke helt, men det kunne kanskje vært noe a la dette:

```typescript
class LastFetchedService {

  setLastFetched(...) {
    // Denne metoden kan kartvisningen, listevisningen
    // evt andre steder oppdatere med sin sist oppdatert dato
    // etter man har byttet visning
  }

  setUpdateSearchFunc(..) {
    // Denne metoden kan kartvisningen, listevisningen osv kalle for
    // å gi beskjed om hvilken metode som skal kalles når man trykker
    // på offrisk-knappen
  }

}
```

Så bruker oppfrisk-knapp-komponenten denne servicen.

Et alternativ tror jeg er å ikke vise sist oppdatert dato på web, kun hvis det er brukt offline-søk.

2022-12-19 12:15 UTC, jorgkv commented on src/app/modules/map/components/map/map.component.ts
> +    this.fullscreenService.isFullscreen$.pipe(skip(1), takeUntil(this.ngDestroy$)).subscribe(() => {
Hvorfor `skip(1)` her? Gjerne legg til en kommentar, eller hvis `isFullscreen$` ikke fungerer som tenkt, bør det heller løses der?

2022-12-19 12:37 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +export function withinExtentCriteriaToBounds(extent: WithinExtentCriteriaDto): L.LatLngBounds {
Nja, de kunne vel likegodt ligget i en egen util-sak. Det var vel fordi denne servicen har ansvar for å håndtere søkekriteria, så jeg syntes det var logisk. Men sikkert ryddigere å ha den et annet sted, skal fikse

2022-12-19 12:40 UTC, gruble commented on src/app/core/services/search-registration/search-registration.service.ts
> +  private lastFetched = new Subject<Date>();
Bra fanget opp! Jeg synes løsningsforslaget ditt var bra. Prøver å gjøre det på den måten.

2022-12-19 12:41 UTC, gruble commented on src/app/modules/map/components/map/map.component.ts
> +    this.fullscreenService.isFullscreen$.pipe(skip(1), takeUntil(this.ngDestroy$)).subscribe(() => {
Godt poeng. Vi har vel ikke bruk for at isFullscreen$ begynner å mase før man faktisk velger fullskjerm, så jeg løser det der

2022-12-20 14:47 UTC, gruble commented on src/app/core/services/search-registration/search-registration.service.ts
> +  private lastFetched = new Subject<Date>();
Har laget en egen service for dette som du foreslo. Dette funker sånn noenlunde. Jeg har problemer med to ting:

1. Oppfrisk-knapp i filterpanel når kartfanen er aktiv, trigger ikke søk på nytt, selv om jeg ser at HomePage får det med seg. Ser dette i loggen når jeg trykker oppfrisk-knappen når listefanen er aktiv.
2. Spinner var ikke helt til å stole på, så jeg har tatt den bort midlertidig og nøyer meg med å fjerne "oppdatert-tidspunkt" når man trykker på oppfrisk-knappen.

2022-12-21 11:37 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +export function withinExtentCriteriaToBounds(extent: WithinExtentCriteriaDto): L.LatLngBounds {
Har flytta dem til HomePage nå siden det er kun denne sida som bruker dem.

2022-12-21 11:44 UTC, gruble commented on src/app/modules/map/components/map/map.component.ts
> +    this.fullscreenService.isFullscreen$.pipe(skip(1), takeUntil(this.ngDestroy$)).subscribe(() => {
Har gjort flere forsøk i FullscreenService på å vente med å sende ticks på isFullscreen$. Det funker forsåvidt, men av en eller annen grunn fører dette til at det blir trigget flere søk etter observasjoner under oppstart. Skulle gjerne visst hvorfor.
Løsningen nå er å la være å skippe første tick på isFullscreen$ i MapComponent. Dette gjør at vi får flere ticks på MapService.mapView$, men siden vi i HomePage uansett venter til vi får searchCriteria$ med et skikkelig kartutsnitt, trigges ikke flere søk under oppstart. Jeg løser det på denne måten i linje 176 i HomePage:
`await firstValueFrom(this.mapService.relevantMapChangeWithInitialView$)`
Hadde jo vært gunstig å kunne fyre av søket tidligere, men dette er min løsning inntil vi finner på noe bedre.

2022-12-22 10:35 UTC, widforss requested changes
Ser bra ut. To ting, refresh()-greia føles alvorligere enn zoom-søket, som er mer frivillig.

2022-12-22 10:35 UTC, widforss commented on src/app/pages/home/home.page.ts
> +            return false; //will stop this criteria change to propagate when we zoom in
Her går det å forbedre (hvis man vil). Hvis jeg navigerer sånn her (`[xmin, ymin, xmax, ymax]`):
1. `[0, 0, 100, 100]`
2. `[50, 50, 90, 90]`
3. `[40, 40, 80, 80]`
4. `[80, 40, 120, 80]`

Så vil det i nåværende løsning skje et søk allerede på steg 3, selv om det ikke er nødvendig før vi går ut fra vår originale bbox som vi hadde i steg 1.

2022-12-22 10:35 UTC, widforss commented on src/app/modules/side-menu/components/update-observations/update-observations.component.html
> +<ion-item (click)="refresh()">
Som jeg skjønner koden her er det eneste som skjer når jeg klikker på knappen her er at du kjører .next() på en tom Observable? Det hentes i hvert fall ikke noenting.

2022-12-22 14:29 UTC, gruble commented on src/app/pages/home/home.page.ts
> +            return false; //will stop this criteria change to propagate when we zoom in
Bra forslag! Jeg har fikset det nå.

2022-12-22 14:35 UTC, merged