observation search criteria
NVE/regObs4 pull request #394
Opened 2022-12-07 13:34 UTC by amish1188

Søke etter observasjons type.
Henter alternativer i checbox liste fra kdv elementer og så sorterer basert på natur fare. 
Søke kriteria støttes av url parametere og. altså hvis man skriver type=81.13~82.26~82.33~13 burde appen søke etter 
[
  {Id:81, SubTypes: [13]},
  {Id:82, SubTypes: [26, 33]},
  {Id:13, SubTypes:[]}
]

2022-12-07 14:18 UTC, gruble commented
Kan du fikse tittelen på PR så den beskriver mer presist hva denne PR'en inneholder? Ta gjerne med saksnummer fra Jira også.

Det er også noe rart med visning av beskrivelsen:
![image](https://user-images.githubusercontent.com/71138449/206202499-4f28239a-95ff-4951-bbec-7d5793c2ee8d.png)

2022-12-07 15:35 UTC, gruble requested changes
Virket ganske bra, synes jeg. Fant en feil når jeg skrev type=82 i url:
![image](https://user-images.githubusercontent.com/71138449/206221553-6c342cf6-454f-45b2-a8b6-978b764864db.png)

Hvis du ikke støtter at man kan søke på bare hovedtyper i URL, tror jeg du kan forenkle koden noe. URL'en blir også enklere, for da kan du droppe både å lese og skrive hovedtyper i URL. Hovedtype må sikkert uansett settes i searchCriteria, men den finner du vel i kdv-elementene?

2022-12-07 15:35 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +    //check that current criteria contains expected nick name
Den kommentaren skjønte jeg ikke mye av, men jeg ser jo hvor du har stjålet koden fra;-)

2022-12-07 15:35 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +
Bra. Jeg ønsker meg flere tester av url-parameteren, siden det er lov å skrive hva som helst i en url. F.eks. å bruke "ulovlige" tegn eller noe annet enn punktum som skilletegn mellom hovedtype og undertype. Hva med å bare sende inn hovedtype uten undertype? Du bruker dette som eksempel i PR, men virker det?

2022-12-07 15:35 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +
Hadde vært fint med en test av removeObservationType() også

2022-12-07 15:35 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  //
Hva hadde du tenkt å skrive i denne kommentaren?

2022-12-07 15:35 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
>      <!-- TODO: Oversettelser på all tekst -->
Dette kan du vel fjerne nå?

2022-12-08 11:23 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +
lagde en regex på den

2022-12-08 16:35 UTC, gruble commented
> Virket ganske bra, synes jeg. Fant en feil når jeg skrev type=82 i url: ![image](https://user-images.githubusercontent.com/71138449/206221553-6c342cf6-454f-45b2-a8b6-978b764864db.png)
> 
> Hvis du ikke støtter at man kan søke på bare hovedtyper i URL, tror jeg du kan forenkle koden noe. URL'en blir også enklere, for da kan du droppe både å lese og skrive hovedtyper i URL. Hovedtype må sikkert uansett settes i searchCriteria, men den finner du vel i kdv-elementene?

Det er bra du har fikset slik at filter på kun hovedtype i URL ikke kræsjer, f.eks. type=82. Men hvis jeg setter type=82 i URL, får jeg ikke filter på alle undertypene under 82. Hvis du ikke har tenkt å fikse dette, trenger du ikke så avansert URL-støtte, tror jeg. Hvis det er vanskelig å skjønne hva jeg mener, spør meg gjerne imorra.
Gamle regobs.no støtter dette. Se f.eks.:
[(https://test.regobs.no/observation/search/list?SelectedNumberOfDays=3&GeoHazards=10&Countries=578&SelectedRegistrationTypes=%7B%22Id%22:82%7D)]

2022-12-09 13:48 UTC, gruble approved these changes
Denne vises fortsatt selv om den ikke virker:
![image](https://user-images.githubusercontent.com/71138449/206716524-d1358546-365f-4c10-9508-1cc0841372f0.png)

2022-12-09 13:48 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +    </ion-item>
Husk å skjule filter på observatør og tilbakestill-knapp til dette virker

2022-12-09 13:48 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +
Fint, og det ser ut til å virke. Men hvor tester du at regex'en filtrerer vekk ulovlige parametre?

2022-12-13 10:40 UTC, merged