disbaled swipe
NVE/regObs4 pull request #398
Opened 2022-12-13 09:46 UTC by amish1188

Swipe er nå disabled på overview og obs location siden. Den er satt på som default på home page. Da jeg satt opp [swipeGesture]="swipeBackEnabled$ på ion-menu så kunne jeg ikke få swipen på som default når man starter appen. Å sette den i inn i konstruktoren i swipeService ga ikke noe resultat.

2022-12-14 11:43 UTC, jorgkv requested changes
Se kommentar i app.component.html

2022-12-14 11:43 UTC, jorgkv commented on src/app/app.component.html
> +  <ion-menu [swipeGesture]="swipeBackEnabled$ | async" side="start" menuId="filter" contentId="main-content">
Jeg tror egentlig det holder å sette `maxEdgeStart="0"` her, som for den andre menyen. Da slipper vi også endringene i de andre filene.

2023-01-26 13:18 UTC, robinzaal approved these changes

2023-01-26 13:18 UTC, robinzaal commented on src/app/app.component.html
> -  <ion-menu side="start" menuId="filter" contentId="main-content" style="--background: #fff">
Hvorfor er `style` fjernet her? Det ble lagt på i en tidligere PR for å gi hele venstremenyen hvit bakgrunn.

2023-01-26 13:24 UTC, merged