Legge til filter på fra- og til-dato
NVE/regObs4 pull request #399
Opened 2022-12-13 13:29 UTC by robinzaal

Oppdatert SearchCriteriaService med støtte for fromDate og toDate, samt lagt til ny komponent for å velge forhåndsvalgt dato tilbake i tid eller et brukersatt datointervall.

2022-12-14 15:07 UTC, jorgkv requested changes
Jeg er fortsatt litt usikker på hva vi skal gjøre med de to testene som feiler og med daysBack i userSettings. Du kan se på det jeg har kommentert på her først.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.ts
> +  minDate = new Date('01.01.2010').toISOString();
Dette feiler i safari fordi new Date(...) forventer en string på ISO 8601-format. Andre browsere er litt snillere på parsingen. Siden du uansett gjør om datoen til en string, så er det kanskje like greit å bare skrive iso-stringen direkte?

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    }
Lag heller et objekt som sendes vha next i bunnen av funksjonen, så unngår vi at det blir to ticks for de som lytter på searchCriteriaChanges.

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  setToDate(toDate: string) {
Jeg tror det er lurt å gjøre om typen på toDate og fromDate til Date. Da slipper brukere av disse funksjonene å vite noe om hvordan stringen skal se ut. Konverteringen fra Date til string kan du lage i en egen funksjon her som eventuelt kan enhetstestes.

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +      return {
Dette er ikke en endring som er relatert til det denne PRen skal løse.

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +        const _criteria = { ...criteria } as SearchCriteriaRequestDto;
Hvorfor må du lage en kopi av `criteria` her?

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +function shorthandDateToIsoDateTime(date: string): string {
Dette er typisk en funksjon som det kan være kjekt å lage en enhetstest til

2022-12-14 15:07 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    return [...UrlDtoOrderByMap].find(([, val]) => val == value)[0];
Dette er ikke en endring som er relatert til det denne PRen skal løse.

2022-12-14 15:07 UTC, jorgkv commented on src/app/app.component.html
> +  <ion-menu side="start" menuId="filter" contentId="main-content" style="--background: #fff">
Dette er ikke en endring som er relatert til det denne PRen skal løse.

2022-12-14 15:07 UTC, jorgkv commented on src/app/components/datetime-picker/datetime-picker.component.ts
> - * Component for displaying a date and time picker.
Hvorfor fjernes denne dokumentasjonen? Jeg syns vi bør beholde minst de to linjene som beskriver hva komponenten gjør.

2022-12-14 15:07 UTC, jorgkv commented on src/app/components/datetime-picker/datetime-picker.component.ts
> +  @Input() size: 'small' | 'default' | 'large' = 'default';
Legg til en kommentar som beskriver hva size brukes til / hvordan det forandrer utseende på komponenten. Det er ikke mulig å skjønne uten å grave i koden eller teste.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.html
> +            <ion-radio [value]="'predefined'" slot="start" (click)="changeDateAndSetMode()"></ion-radio>
Legg til `Mode`-enumen som en readonly property på komponentet. Da kan du referere til selve enum-verdiene i templaten, vi slipper at enumen og templaten eventuelt kommer ut av sync hvis man oppdaterer ett av stedene.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.html
> +              [minDate]="minDate"
minDate her bør være fromDate eller fromDate + 1 dag. Nå kan man velge datointervaller som ikke gir mening med startdato etter sluttdato.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.html
> +              [textAlign]="'right'"
Hvis du bare skal gi en statisk string så holder det med `textAlign="right"` vil jeg tro. Gjelder alle steder du angir statiske strings.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.scss
> +ion-radio-group ion-item .item-bottom {
Jeg klarer ikke se at dette blir brukt i koden. Kan du legge til en kommentar som forklarer hvorfor denne css-en er her?

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.scss
> +  border-bottom: 1px solid #dedede;
`ion-item.no-border:last-child::part(native)` sleit jeg med å forstå hvorfor vi trenger. Gjerne beskriv med en kommentar hvorfor vi trenger den.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/date-range/date-range.component.ts
> +  get modeText(): Observable<string> {
Jeg vet ikke om det er en god idé å returnere en observable fra en getter på denne måten. Kan være det fungerer OK, men jeg prøvde å legge til logging i observablene som returneres, og da ser man at det logges ganske mange ganger når man endrer språk osv.

Det er mulig det er bedre å gjøre om mode til en BehaviourSubject og modeText til en observable basert på mode i stedet for en getter?

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +  <app-date-range></app-date-range>
Husk at `<app-observations-days-back>` fortsatt skal brukes på mobil.

2022-12-14 15:07 UTC, jorgkv commented on src/app/modules/side-menu/components/observations-days-back/observations-days-back.component.html
> +<ion-select
Husk at denne komponenten fortsatt skal brukes selvstendig på mobil. Sjekk at det fortsatt fungerer etter disse endringene.

2022-12-14 15:07 UTC, jorgkv commented on src/assets/i18n/nb.json
> +    "DATE_RANGE": {
Nå har vi både "DAYS_BACK" og "WEEKS_BACK" pluss disse nye tekstene, som skal vise omtrent det samme. Jeg foreslår at du fjerner DAYS_BACK og WEEKS_BACK og bruker de nye tekstene i dropdownen og eventuelt andre steder i appen de gamle tekstene ble brukt.

2022-12-14 15:42 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  setToDate(toDate: string) {
Du får se litt på hvordan dette er satt opp i dato-komponenten, og om det gir mening å bruke dato eller ikke. Men jeg tror de fleste datepickere har en valueAsDate du kan bruke for å få verdien som dato-objekt.

2022-12-14 15:43 UTC, jorgkv commented on src/assets/i18n/nb.json
> +    "DATE_RANGE": {
Husk også å kjøre `npm run translations:sort` etter du har lagt til nye nøkler.

2022-12-20 15:38 UTC, jorgkv commented
@robinzaal kan du se på konfliktene?

2022-12-20 17:46 UTC, robinzaal commented
@jorgkv resolvet det som lå der

2022-12-21 14:29 UTC, gruble requested changes
Jeg får ikke til å søke på "Kun dagens observasjoner":
Radioknappen blir satt på for egendefinert periode i stedet
Hvis jeg skrur på radioknappen foran "kun dagens observasjoner" etterpå, blir ikke søkekriteria satt riktig

2022-12-22 08:03 UTC, gruble requested changes
![image](https://user-images.githubusercontent.com/71138449/209086550-ce26ee63-fedb-4187-ba93-6c8b289b71e5.png)

- Stor K i "Kun..." 
- 52 uker tilbake trenger vi ikke når vi kan bestemme fra-dato selv- Den var kun med for testing av store søk

2022-12-22 08:19 UTC, gruble requested changes
Hvis jeg setter sluttdato, får jeg ikke med meg observasjoner fra den dagen. Det vil jeg ha. En mer presis ledetekst hadde kanskje "Fra og med dato" og "Til og med dato"
![image](https://user-images.githubusercontent.com/71138449/209088624-42a5f19d-323a-4464-a7d4-bc530e2f99c6.png)

2022-12-22 08:22 UTC, gruble requested changes
Jeg finner ingen måte å ta bort startdato eller sluttdato når jeg først har valgt det. Det trenger vi.

2022-12-22 08:33 UTC, gruble requested changes
Hvis jeg kun setter til-dato i URL, blir fra-dato satt til dagens dato og jeg får et søk som ikke gir mening:
![image](https://user-images.githubusercontent.com/71138449/209092052-c9f0b979-3dee-4e00-91be-2b618ec92b6b.png)

2022-12-22 10:09 UTC, gruble requested changes

2022-12-22 10:09 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +    tick(100);
Disse testene ligger i suiten for test av url-parsing. De hadde vært enklere å skrive om de lå den andre suiten, for da instansieres servicen automatisk. Gjelder flg. tester:

- 'fromDate url param should be set or updated'
- 'toDate url param should be set or updated'
- 'toDate url param should be removed when updating fromDate with true'

2022-12-22 10:09 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
>  });
Det mangler tester av parsing av query-parametrene fromDate og toDate

2022-12-22 10:09 UTC, gruble commented on src/assets/i18n/nb.json
>      "TIME_FRAME": "Tidsrom",
Ser ikke ut som denne er i bruk, så den kan du sikkert fjerne

2023-01-10 15:12 UTC, gruble requested changes
Fortsatt noen kommentarer som ikke er behandlet. Fant også noen nye feil.

2023-01-10 15:12 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +        map((daysBack) => isoDateTimeToLocalDate(this.daysBackToIsoDateTime(daysBack)))
Hvorfor konverterer du først til iso-tid og deretter til lokal tid?

2023-01-10 15:12 UTC, gruble commented on src/app/modules/side-menu/components/observations-days-back/observations-days-back.component.html
> +  <ion-select-option *ngFor="let item of daysBackOptions" [value]="item.val">
Nedtrekkslista inneholder fortsatt valget 52 uker tilbake. Det skal ikke være med.

2023-01-10 15:12 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +    const expectedToTime = moment(new Date('2022-12-24 00:00:00.000')).toISOString(true);
expectedToTime skal vel være 1 døgn seinere enn dette, så vi får med alle observasjoner på julaften?
Dette søket tror jeg ikke ville returnere noen observasjoner.

2023-01-10 15:12 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +    expect(criteria.ToDtObsTime).toEqual('2000-12-24T00:00:00.000+01:00');
Denne testen feiler hos meg. Har du kjørt testene?

2023-01-12 16:34 UTC, gruble approved these changes
Endelig!-) Funker bra nå

2023-01-16 08:47 UTC, merged