Bugfix/competence filter automatic stations
NVE/regObs4 pull request #403
Opened 2022-12-15 12:44 UTC by amish1188

vi dropper ukjente kompetanser og bruker 'alle' istedenfor. nå funker checkbox på automatiske stasjoner som den burde, altså når alle kompetanser er valgt i dropdownen og automatiske stasjoner er avsjekket så filtrerer appen på alle kompetanser bortsett fra automatiske stasjoner (id: 105)

2022-12-16 10:53 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +  <ion-list-header color="varsom-blue" class="ion-no-margin">
jeg fjernet div tag så alle linjer skiftet

2022-12-19 10:17 UTC, gruble requested changes
Automatiske stasjoner vises ikke, selv om jeg velger det i filteret

2022-12-19 10:17 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +        {{ co.name }}
![image](https://user-images.githubusercontent.com/71138449/208398893-42b3c9ec-7b35-4987-8a95-290edc2fe5bc.png)
"All" må oversettes

2022-12-19 12:26 UTC, gruble requested changes
Funker bra nå. Bare pirk igjen.

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +    <ion-label> Observasjonstype </ion-label>
Oversettelse

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +  <!-- TODO: Legg til eller hente kompetanser i menyen. Husk at på snø er det en spesiell kompetanse A -->
Er du ferdig? Jeg lurer på hvorfor denne TODO'en står her?

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  chosenCompetenceValue;
hvilken type er dette?

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  async isObserverCompetence(sc: number[], compLevels) {
Hva er "sc" til? kan du lage et variabelnavn som er mer selvforklarende eller legge til dokumentasjon?

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  async isObserverCompetence(sc: number[], compLevels) {
Parametrene mangler typer

2022-12-19 12:26 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  async sortCompetences(unsortedCompetences: KdvElement[][]): Promise<CompetenceItem[]> {
Du har flere funksjoner som ikke trenger å være tilgjengelig utenfor klassen. Hva med å sette disse som private?

2022-12-19 14:51 UTC, gruble approved these changes

2022-12-20 08:04 UTC, merged