Task/ro 2054/list all or mapview
NVE/regObs4 pull request #416
Opened 2023-01-04 12:32 UTC by amish1188

Lagt til koordinater i params. Skal vises bare 4 decimaler. Hvis man skriver riktige params i urlen så burde kartet vise et riktig sted. 
Av og til hvis jeg skriver params i feil format (altså flere enn 4 decimaler) så zoomes kartet ut og viser hele verden. Kunne ikke finne ut hva som egentlig er problemet her. Skjedde bare et par ganger.  

Hvis jeg starter appen med /registration/new istedenfor home siden, og setter koordinater i urlen så viser en riktig sted på ny observajons kart. men hvis jeg drar tilbake til hoved skjermen med tilbake knapp så blir karten zoomet ut til maks og jeg ser hele verden (koordinater endres også). ser ut at den setter en 'default' kartutsnitt. Lurer på om det er noe sted hvor vi kunne lagre (eller lagrer) en riktig kartutsnitt til home siden selv om man starter på registration siden? Eller kanskje det ikke er så vikitg?

2023-01-11 12:45 UTC, jorgkv requested changes

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +  it('too many decimals in coordinates in url', fakeAsync(async () => {
Hva er forskjellen på denne testen og testen over, de ser helt like ut?

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +      const nwLatToNum = (+nwLat).toFixed(4);
Du trenger ikke fjerne desimaler når du leser koordinater. Hvis folk ønsker å oppgi et veldig presist kartutsnitt så skal de få lov til det.

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  setExtent(value: string) {
Bruk helst sterkere type enn dette, hvis det er to konkrete strings denne skal kunne motta.

2023-01-11 12:45 UTC, jorgkv commented on src/app/modules/map/components/map/map.component.ts
> +  private bounds;
Husk type her

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +const URL_PARAM_NW_LAT = 'nwlat';
Bruk nwLat osv

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    this.readCoordinates(
Jeg tror det blir bedre om dette flyttes til mapService, og kjøres i constructoren til mapService.
Bruk URL_PARAMS_NW_LAT osv fra denne fila likevel. Det kan hende du må flytte de variablene som brukes av begge servicer til en egen fil for å unngå sirkulære referanser.

2023-01-11 12:45 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +      map(([criteria, langKey, geoHazards, fromObsTime, showMapExtent, extent]) => {
useMapExtent er bedre enn showMapExtent, siden denne styrer om man filtrerer på map extent eller ikke, ikke bare om det vises i urlen

2023-01-11 12:45 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.html
> +                <ion-label>I kartutsnitt</ion-label>
Husk oversettelser, norsk og engelsk

2023-01-11 12:45 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  segmentValue: string;
Bruk sterkere type her hvis det bare er to mulige strings denne kan settes til

2023-01-11 12:51 UTC, jorgkv commented
Husk også å fikse toggle når man starter opp uten extent som søkrekriterier

2023-01-12 10:09 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +  it('too many decimals in coordinates in url', fakeAsync(async () => {
sant, tror jeg kan droppe den øverst en

2023-01-12 10:14 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +      const nwLatToNum = (+nwLat).toFixed(4);
done

2023-01-12 10:18 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  setExtent(value: string) {
yes sir

2023-01-12 11:05 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +const URL_PARAM_NW_LAT = 'nwlat';
ok

2023-01-12 11:05 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    this.readCoordinates(
flyttet

2023-01-13 10:07 UTC, amish1188 commented on src/app/modules/shared/coordinatesUrl.ts
> +export const URL_PARAM_NW_LAT = 'nwLat';
Jeg vet ikke om det var det du mente med å få 'shared' elementer til en separat fil?

2023-01-13 15:41 UTC, jorgkv requested changes

2023-01-13 15:41 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.spec.ts
> +  it('extent filter', fakeAsync(async () => {
Du må ha en bedre tittel her, "extent filter" er ikke god nok beskrivelse på en test.

2023-01-13 15:41 UTC, jorgkv commented on src/app/modules/shared/coordinatesUrl.ts
> +export const URL_PARAM_NW_LAT = 'nwLat';
Jo, det er fint, men den bør nok ikke ligge i denne mappen.

"modules"-mappa inneolder angular-moduler.
"modules/shared" inneholder angular-modulen "shared".
Siden denne fila ikke er en del av shared-modulen bør den ikke ligge her.

Det er bedre om den ligger i feks core/services/search-criteria.

2023-01-13 15:41 UTC, jorgkv commented on src/app/modules/map/services/map/parseCoordinates.spec.ts
> +    const mapView = parseCoordinatesFromUrl(new URL(document.location.href));
Du trenger ikke bruke UrlParams her. Det er bedre å bare bruke `new URL('https://regobs.no?nwLat=...')`.
Hold en enhetstest så liten som mulig. Hva er det du ønsker å teste her? Det er jo `parseCoordinatesFromUrl`-funksjonen, ikke `new UrlParams().set .....apply()`, det kan testes i en annen enhetstest.

2023-01-13 15:41 UTC, jorgkv commented on src/app/modules/map/services/map/parseCoordinates.spec.ts
> +      Object({ _southWest: new LatLng(67.5715, 21.4343), _northEast: new LatLng(70.79781234, 33.1458) })
Ikke bruk interne egenskaper på leaflet bounds når du tester. Bruk heller apiet til bounds, feks getSouthWest.

2023-01-13 15:41 UTC, jorgkv commented on src/app/modules/map/services/map/map.service.ts
> +//sometimes the map changes the zoom and shows the entire globe instead of zoomed area (happens for example if you start app in registration page
Denne kommentaren her er det vel bedre å fikse eller legge inn som en bug i JIra. Får du fiksa det tror du?

2023-01-13 15:41 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +        return {
Gjør det gjerne om igjen til bare å returnere objektet direkte.

2023-01-13 15:41 UTC, jorgkv commented on src/assets/i18n/nb.json
> +    "IN_MAP_VIEW": "I kartutsnitt",
Lag heller nye nøkler for dette. Bruk

`TOGGLE_BUTTON_OBSERVATIONS_ALL` og `TOGGLE_BUTTON_OBSERVATIONS_IN_MAP_VIEW`

Så blir det enklere for oversetterne å skjønne hvor det brukes.
Hvis de gamle nøklene ikke er i bruk lenger kan de slettes.

2023-01-13 15:41 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  segmentValue: MapSectionFilter;
Du kan bare sette `segmentValue: MapSerctionFilter = 'mapBorders'` her, så sparer vi en linje i constructoren.

2023-01-13 15:41 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  segmentValue: MapSectionFilter;
Når man starter applikasjonen på listevisninga må segmentValue være satt til 'all'. Hvis ikke ser det litt rart ut selv om segment-knappen er deaktivert.

2023-01-13 15:41 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  checkIsCoordinates() {
Dette med `checkIsCoordinates` og `coordinatesFromParams` er ikke løst så bra.
Hvis vi har et map extent, så kan vi vise togglen. Trenger ikke sjekke hva som er i urlen. Jeg sjekka inn en fiks på dette, se hvordan jeg løste det i den commiten.

2023-01-13 15:42 UTC, jorgkv commented on src/app/modules/map/services/map/map.service.ts
> +//sometimes the map changes the zoom and shows the entire globe instead of zoomed area (happens for example if you start app in registration page
Mulig jeg har fiksa dette i en av commitene jeg sjekka inn. Gjerne test dette og fjern kommentaren hvis det stemmer.

2023-01-16 07:51 UTC, amish1188 commented on src/app/modules/map/services/map/map.service.ts
> +//sometimes the map changes the zoom and shows the entire globe instead of zoomed area (happens for example if you start app in registration page
det virker løst nå

2023-01-16 07:55 UTC, amish1188 commented on src/app/pages/observation-list/observation-list.page.ts
> +  segmentValue: MapSectionFilter;
jeg baserte verdi på mapview subscription. hvis det finnes mapview så blir det 'mapBorders' hvis ikke så har vi alle

2023-01-18 10:47 UTC, jorgkv requested changes
Hent inn det siste fra develop og test litt, pluss fiks det jeg har kommentert her, så kan jeg ta en titt til.

2023-01-18 10:47 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    value == 'all' ? this.useMapExtent$.next(true) : this.useMapExtent$.next(false);
Dette kan vel ikke stemme? Hvis man sender inn 'all' så skal extent brukes, men hvis man sender inn 'mapBorders' så skal extent ikke brukes?

2023-01-18 10:47 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +        Extent: !useMapExtent ? extent : null,
Hvis `!useMapExtent` så skal extent brukes ellers null? Dette stemmer ikke.

2023-01-18 10:47 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    value == 'all' ? this.useMapExtent$.next(true) : this.useMapExtent$.next(false);
Jeg tror også det er bedre å bare gjøre om metoden til feks `setExtentFilterActive(extentFilterActive: boolean)`. `MapSectionFilter` kan du bare flytte til `observation-list.page.ts`.

2023-01-18 10:47 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  useMapExtent$: Subject<boolean> = new BehaviorSubject<boolean>(false); //TODO: Trenger vi en funksjon for å skru av filter på kartutsnitt?
Det er vanlig å bruke `$` som suffix på observables, men dette er en subject som vi ikke trenger å eksponere direkte. Kan du gjøre denne private igjen, og så lage en public getter som gir ut en observable basert på subjecten?

```typescript
get useMapExtent$() {
  return this.useMapExtent.asObservable();
}
```

2023-01-18 11:22 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    value == 'all' ? this.useMapExtent$.next(true) : this.useMapExtent$.next(false);
det stemmer. jeg miksa ting her.

2023-01-18 11:22 UTC, amish1188 commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +        Extent: !useMapExtent ? extent : null,
fikset

2023-01-20 09:29 UTC, jorgkv requested changes

2023-01-20 09:29 UTC, jorgkv commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +  private useMapExtent: Subject<boolean> = new BehaviorSubject<boolean>(true); //TODO: Trenger vi en funksjon for å skru av filter på kartutsnitt?
Denne kommentaren kan fjernes - den funksjonen har jo du laget..

2023-01-20 09:29 UTC, jorgkv commented on src/assets/i18n/nb.json
> +    "ALL_OBSERVATIONS": "Alle",
Denne endres, men brukes ikke lenger. ALL_OBSERVATIONS bør vel heller fjernes? Mener jeg nevnte dette i en tidligere kommentar også.

2023-01-20 09:29 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  toggleFilterByMapView(event) {
Legg til type på denne eventen. Se https://ionicframework.com/docs/api/segment#segmentcustomevent . Ser ut som det er riktigere å bruke `event.detail.value` ?

2023-01-20 09:29 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +  toggleFilterByMapView(event) {
I tillegg, se tidligere kommentar: https://github.com/NVE/regObs4/pull/416/files/4924194145b0230af70346f8bb0508ded8e2fd53#r1073369117 

Jeg tror det er bedre å bare sende en bool til searchCriteriaService og endre navn på setExtent.
Når metoden heter setExtent virker det som man kan endre extent ved hjelp av den metoden, det kan man ikke, man kan bare skru filteret av og på.

2023-01-20 10:08 UTC, amish1188 commented on src/app/pages/observation-list/observation-list.page.ts
> +  toggleFilterByMapView(event) {
detail.value eksisterer ikke her. returnerer undefined

2023-01-23 10:43 UTC, jorgkv commented
Hvis man har valgt et kartutsnitt via kartet og går til listevisning så ser man observasjonene for det området. Hvis man deretter starter å registrere en observasjon, zoomer inn til et detaljert zoomnivå uten observasjoner, og går tilbake, så har ikke lenger listevisningen noen observasjoner fordi "ny-obs"-kartet oppdaterer extent. Jeg vet ikke om det er helt bra. I tillegg ser man at at-a-glance og listevisning trigges hele tiden i bakgrunnen selv om man er på ny-obs-kartet hvor ikke observasjoner vises i det hele tatt. Tror heller ikke det er bra. Jeg vet ikke helt hvordan det er best å løse det.

2023-02-03 07:55 UTC, jorgkv approved these changes

2023-02-03 07:56 UTC, merged