Add map component to ModalMap. Add GIF as location symbol for proof
NVE/regObs4 pull request #43
Opened 2021-05-25 08:02 UTC by nicolaimich

- Move map functionality into ModalMapImage. Re-add markers.
- Add a location GIF as symbol for locationMarker for testing purposes. The idea is to have our own GIF in order to have animation in the map. 
- Still to do: I need review in order to help me define what I can clean up of code :)

2021-05-25 13:45 UTC, gruble commented
Tror ikke du trenger å vise støttekart i popup'en. Kanskje MapComponent har en parameter for dette?

2021-05-25 13:59 UTC, gruble approved these changes
Så bra ut!
Ser du viser støttekart i popup'en. Det tror jeg ikke vi trenger; har i hvert fall ikke hatt det før.

2021-05-25 14:14 UTC, gruble reviewed
Litt vanskelig å gi fornuftige tilbakemeldinger på hva du bør fjerne i map-image.component, fordi jeg ikke får lov å kommentere kode du ikke har endret på, men prøver meg på flg.:

- alt som har med start, stopp. og skade-ikoner kan fjernes
- tror ikke du trenger mapCenterSubject, for location endrer seg vel ikke? Men er ikke helt sikker. Hvis denne kan endre seg, bør du vel ta hensyn til denne når du lager bildet?
- map og options kan fjernes
Logikken i isInNorway og addTileLayers kan du beholde (evt. kommentere ut), da jeg tror du vil trenge deler av dette når du skal bruke kart fra Kartverket (som bare gjelder Norge)
- 
-

2021-05-25 14:14 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
>    @Input() allowZoom: boolean;
Bildet er vel statisk nå, så da kan man vel ikke tillate zoom?

2021-05-25 14:14 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
>    onLeafletMapReady(map: L.Map) {
Bare å fjerne

2021-05-25 15:27 UTC, nicolaimich commented
> Så bra ut!
> Ser du viser støttekart i popup'en. Det tror jeg ikke vi trenger; har i hvert fall ikke hatt det før.

Kan vi se på dette sammen imorgen ? :)

2021-05-27 08:22 UTC, gruble requested changes
Fint du fikk vekk støttekartet i popup!

En kommentar om kode som er kommentert ut: Når man treffer på kode som er "kommentert ut" uten noen kommentarer blir man usikker på hvorfor det er kommentert ut, og det blir ikke noe lettere når vi har glemt hvorfor vi gjorde det. Foreslår at du legger inn TODO'er der du kommenterer ut kode om hvorfor du beholder koden.

Ang. funksjonene createIcon()/getIconUrl():  Mener jeg kom med et tips om  hvordan du kunne skrive dette mer effektivt? Gjelder også markerHelper.ts.

2021-05-27 08:22 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
> +/*   ngOnChanges(changes: SimpleChanges & SmartChanges<this>): void {
Foreslår at du finner ut om du trenger dette eller ikke. Hvis ingen bruker mapCenterSubject, kan du bare fjerne denne koden. Når man treffer på kode som er kommentert ut uten kommentarer blir man usikker på hvorfor det er kommentert ut, og det blir ikke noe lettere når vi har glemt hvorfor vi gjorde det.

2021-05-27 08:22 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
> +/*   private isInNorway() {
Kjekt med en kommentar om hvorfor du har kommentert ut. Hvorfor beholder vi det?

2021-05-27 08:22 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
> +    //this.mapCenterSubject = new BehaviorSubject(this.location);
Se kommentar under

2021-05-27 08:22 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
> +  //private mapCenterSubject: BehaviorSubject<ImageLocation>;
Se kommentar om denne lengre ned

2021-05-27 08:22 UTC, gruble commented on src/app/modules/map/components/map-image/map-image.component.ts
> +const DAMAGE_ICON = '/assets/icon/map/damage-location.svg'; */
Disse ikonene har med start, stopp og skade, og kan fjernes

2021-05-28 11:59 UTC, merged