added reset filter on click
NVE/regObs4 pull request #438
Opened 2023-02-01 14:17 UTC by amish1188

Nå abonnerer vi på searchCriteria i filtermeny istedenfor å hente dem bare en gang på starten av appen.

2023-02-02 15:18 UTC, gruble requested changes
Har testet kjapt, og det virker å funke bra. Har en del kommentarer på struktur og kodestil.

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +      <ion-icon src="./assets/icon/reset-button.svg"> </ion-icon>Tilbakestill filtere
Oversettelse

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +      this.nickName = criteria.ObserverNickName;
Dette synes jeg er vanskelig å forstå. En måte å gjøre det lettere er å skille ut noen kodeblokker i egne funksjoner med navn som forklarer hva de gjør.
En annen måte er å legge inn kommentarer.

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  async onRestartFilters() {
Er det noen grunn til at du kaller det restart i motsetning til reset. Starter du filteret på nytt?

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +    this.searchCriteriaService.restartSearchCriteria();
Se kommentar om navngiving over (restart/reset)

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +    if (this.currentGeoHazard.includes(10) && !this.isAutomaticStationChecked && event.detail.value.value === 'All') {
Du kan bruke GeoHazard.Snow i stedet for 10

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  }
Her mangler det litt luft

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
>    onSelectCompetenceChange(event) {
Du kan deklarere typen du får inn her, så får vi litt mer hjelp av typescript-kompilator

2023-02-02 15:18 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +      const removed = copyCriteria.filter((i) => i !== 105);
105 er brukt en drøss ganger i koden. Brudd på OnceAndOnlyOnce. Det blir mange endringer hvis vi en gang endrer ID'en for automatiske stasjoner. Jeg foreslår at du lager en konstant for dette.

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  private async isObserverCompetence(searchCriteriaObserverCompetence: number[]) {
Funksjonsnavn som starter med "is" bør ikke endre noe, de bør kun sjekke ting. Du trenger et navn som beskriver bedre hva denne funksjonen gjør

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  private formatUrlToViewModel(ids: number[]): CompetenceItem {
formatUrlToViewModel trenger et mer beskrivende navn. Navnet sier ingenting om kompetanse. Du leser en array av kompetanse-ID'er, den har ingenting med url å gjøre.

2023-02-02 15:18 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
>    private async sortCompetences(unsortedCompetences: KdvElement[][]): Promise<CompetenceItem[]> {
Bra med kommentarer inni her. 
Denne funksjonen gjør ikke bare sortering, den setter også properties i komponenten. Se om du kan flytte koden som ikke har noe med sortering å gjøre til en annen funksjon eller endre navn på funksjonen

2023-02-02 15:18 UTC, gruble commented on src/app/core/services/search-criteria/search-criteria.service.ts
> +    if (currentObserverCriteria != null && currentObserverCriteria.length > 0) {
Hva med å bruke `currentObserverCriteria?.length` i stedet?-)

2023-02-02 15:19 UTC, gruble requested changes

2023-02-02 15:19 UTC, gruble commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.spec.ts
> +/* import { ComponentFixture, TestBed } from '@angular/core/testing';
Bare fjern denne. Det er ikke noe kode her som er verdt å ta vare på

2023-02-03 09:38 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
> +      <ion-icon src="./assets/icon/reset-button.svg"> </ion-icon>Tilbakestill filtere
done

2023-02-03 10:01 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +      this.nickName = criteria.ObserverNickName;
done

2023-02-06 11:58 UTC, gruble requested changes
Bra. Nå synes jeg koden er mye lettere å forstå.
Har bare 3 kommentarer til så er vi i mål;-)

2023-02-06 11:58 UTC, gruble commented on src/assets/i18n/nb.json
> +    "RESET_FILTER_BUTTON_TITLE": "Tilbakestill filtere"
En liten skrivefeil. Det heter filtre på norsk.

2023-02-06 15:21 UTC, gruble approved these changes

2023-02-07 09:37 UTC, merged