Quick region filter addition
NVE/regObs4 pull request #450
Opened 2023-02-12 23:04 UTC by jorgkv

2023-03-31 06:42 UTC, gruble commented
> Jeg syns ikke det fungerer optimalt med kartutsnitt / ikke kartutsnitt / valg av regioner, hele bruken av togglen er forvirrende. Jeg tror brukere vil lure på hvorfor togglen fins når man ikke kan trykke på den. Men nå fungerer det i hvert fall sånn at søk på extent fjernes om en eller flere regioner er valgt.

Er enig i at folk kanskje vil lure på hvorfor togglen "ikke virker". Men kanskje vi kan løse dette med å skrive en tekst ved siden av med hvorfor den er deaktivert?

2023-04-17 09:11 UTC, amish1188 commented
> > Jeg syns ikke det fungerer optimalt med kartutsnitt / ikke kartutsnitt / valg av regioner, hele bruken av togglen er forvirrende. Jeg tror brukere vil lure på hvorfor togglen fins når man ikke kan trykke på den. Men nå fungerer det i hvert fall sånn at søk på extent fjernes om en eller flere regioner er valgt.
> 
> Er enig i at folk kanskje vil lure på hvorfor togglen "ikke virker". Men kanskje vi kan løse dette med å skrive en tekst ved siden av med hvorfor den er deaktivert?



> > Jeg syns ikke det fungerer optimalt med kartutsnitt / ikke kartutsnitt / valg av regioner, hele bruken av togglen er forvirrende. Jeg tror brukere vil lure på hvorfor togglen fins når man ikke kan trykke på den. Men nå fungerer det i hvert fall sånn at søk på extent fjernes om en eller flere regioner er valgt.
> 
> Er enig i at folk kanskje vil lure på hvorfor togglen "ikke virker". Men kanskje vi kan løse dette med å skrive en tekst ved siden av med hvorfor den er deaktivert?

Lokasjonen forsvinner fra urlen når man velger regioner. Samme skjer når man starter appen på listevisning og kartutsnittet ikke er initialisert. Vil ikke si det blir så forvirrende til brukere men er enig med deg Øystein at vi kunne legge en hjelpe tekst ved siden av toggelen bare når man velger noen regioner (og kanskje også når man starter appen uten kartutsnitt siden det er samme scenario)?

På filter pannelen der hvor det viser hvor mange filtrene ble valgt vil jeg gjerne også ha noe X knapp som fjerner alle filtrene i en seksjon så at det blir enklere å fjerne masse valgene. Men det er bare en fremtids ide :P

2023-04-17 10:53 UTC, amish1188 requested changes

2023-04-17 10:53 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +    this.regions$ = this.userSettingService.currentGeoHazard$.pipe(
Resten av filtrene blir hentet i ngOnInit metoden så jeg bare lurte på om vi kunne bruke enten konstruktoren eller ngOnInit? Tror det kan være litt forvirrende å bruke både til å gjøre samme ting. Du kan bestemme om du vil ha alt i konstruktoren og bare flytte combineLatest metoden fra ngOnInit der.

2023-04-17 10:53 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  private getSnowRegions() {
siden filen er ganske svær kan vi ha alle private metodene på bunnen?

2023-04-17 10:53 UTC, amish1188 commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +  regionCheckBoxChanged(event: CheckboxCustomEvent<AvalancheRegion>) {
vi kan også ha denne metoden under ngOnInit så at andre event metoder blir glad til å være sammen ;)

2023-04-17 10:53 UTC, amish1188 commented on src/app/pages/home/home.page.ts
>        //skip if extent is null (when showing 'all' observations in the list view) to avoid exceptions
Vi trenger ikke denne kommentaren og den på neste linja

2023-04-28 12:22 UTC, jorgkv commented on src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts
> +    this.regions$ = this.userSettingService.currentGeoHazard$.pipe(
Jeg tenker det er greit sånn som det står nå, koden i ngOnInit gjør litt mer, disse linjene lager bare to observables.

2023-04-28 12:27 UTC, amish1188 approved these changes

2023-04-28 12:34 UTC, merged