Task/ro 2043/search reg service in my obs
NVE/regObs4 pull request #469
Opened 2023-02-24 09:30 UTC by amish1188

En ting jeg er usikker på er at vi kanksje burde ha searchMyRegistrations i search-registration.service.ts uten searchCriteria$ parameter og bare implementere searchCriteria$ i selve metoden. men samtidig vi må hente LangKey info og det kommer fra usersettings subscription så kanskje det er bedre å ha det i sent-list.component. Hvis du har noe bedre forslag gjerne si fra

2023-02-24 10:31 UTC, gruble requested changes
Jeg likt løsninga du hadde valgt med å sende søkekriteria inn til SearchRegistrationService.
Mye bra her. Har noen kommentarer.

2023-02-24 10:31 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +    this.userSettingService.language$.subscribe((langKey) => {
Fare for minnelekkasje når du ikke av-abonnerer på observables når komponenten dør

2023-02-24 10:31 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .pipe(tap(() => this.scroll && this.scroll.complete()))
Hvorfor gjør du dette?

2023-02-24 10:31 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +    this.searchResult.registrations$
Se kommentar om minnelekkasje over

2023-02-24 10:31 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .subscribe((myRegistrations) => {
Du henter "mine observasjoner" to ganger fra API'et når du går inn på sida:
![image](https://user-images.githubusercontent.com/71138449/221153089-df6ec761-db2b-4654-bae9-fc712c294b3e.png)

2023-02-24 10:31 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
>    myObservationsUrl$: Observable<string>;
Hva bruker du denne til?

2023-02-24 10:35 UTC, gruble requested changes

2023-02-24 10:35 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .subscribe((myRegistrations) => {
Sida bare står og snurrer hvis API-kallet feiler. Det hjelper heller ikke å kjøre oppfrisk etter at jeg er online igjen. Det er samme feil i "vanlig" listevisning.
![image](https://user-images.githubusercontent.com/71138449/221157021-a716fe88-fe97-40c2-8b1f-467028cb4063.png)

2023-02-24 11:01 UTC, gruble requested changes

2023-02-24 11:01 UTC, gruble commented on src/app/core/services/search-registration/search-registration.service.ts
> +      (searchCriteria) => this.searchService.SearchCount(searchCriteria).pipe(map((result) => result.TotalMatches))
Dette gir deg nok feil tall, for her har du ikke filter på observatøren. Jeg tror du enten finne en måte å filtrere på observatør på eller implementere en funksjon i API'et for å hente antall av "mine observasjoner".

2023-02-24 13:11 UTC, amish1188 commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .pipe(tap(() => this.scroll && this.scroll.complete()))
ion infinite scroll må kalle complete() når lista er ferdig. det er gjort på samme måte i observations-list

2023-02-24 13:12 UTC, amish1188 commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
>    myObservationsUrl$: Observable<string>;
fjernet

2023-02-24 13:12 UTC, amish1188 commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .subscribe((myRegistrations) => {
vi kanksje burde lage en separat task på det

2023-02-27 10:51 UTC, gruble requested changes
Bra. Noen småting igjen

2023-02-27 10:51 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
>    myObservationsUrl$: Observable<string>;
Fint du fjernet refreshFunc hvis du ikke bruker den, men kommentaren gjaldt myObservationsUrl$

2023-02-27 10:51 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .subscribe((newRegistration) => {
Dette variabelnavnet er villedende. Er det bare for nye registreringer eller gjelder det også registreringer som er endret?

2023-02-27 10:51 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .subscribe((myRegistrations) => {
Ok. Jeg har gjort litt om på denne:  https://nveprojects.atlassian.net/browse/RO-1808

2023-02-27 10:51 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
>      this.loggingService.debug('Refresh', DEBUG_TAG);
Denne logginga var sikkert nyttig mens du lette etter feil, men er kanskje ikke så nyttig nå lengre?

2023-02-27 10:51 UTC, gruble commented on src/app/pages/my-observations/components/sent-list/sent-list.component.ts
> +      .pipe(takeUntil(this.ngDestroy$))
Du bør kanskje også håndtere slettede registreringer. Se addUpdateDeleteRegistrationService.deletedRegistrationIds$

2023-02-27 11:26 UTC, gruble approved these changes

2023-02-27 11:56 UTC, merged