RO:2215 sync offline db with deleted registrations
NVE/regObs4 pull request #484
Opened 2023-03-09 12:20 UTC by amish1188

VITKIG: Vi må godkjenne dette først https://dev.azure.com/NVE-devops/Varsom%20Regobs/_git/regobs/pullrequest/3363 

Sjekker om count i api og appen er lik fra den siste synkroniseringen. Hvis api har mindre observasjoner enn app så betyr det at en del må slettes. Tror det kunne vært nyttig og ha en separat kolonne i databasen med syncLastDeleted eller noe så at vi ikke må alltid hente regids fra de to siste ukene men kun fra perioden når sist sletting skjedde. Men det er bare et forslag
Aner ikke hvordan å refreshe observasjoner på kartet etter de blir synket med slettede observasjoner. De forsvinner når jeg flytter på kartet altså når en ny 'api kjøring' skjer. Vet ikke hvordan å bruke det i offline service.

Sletting funka ikke på iphone lokalt hos meg dessverre. Dere kan gjerne teste det selv. Kanskje vi trenger noe mer konfigurasjon? Vanskelig å finne noe på nettet. Den fungerer pent på android.

2023-03-09 18:48 UTC, gruble commented
For å tvinge kartet til å oppdatere seg, foreslår jeg at du kan prøve samme mekanisme som oppfrisk-knappen bruker, altså UpdateObservationsService.requestRefresh()

2023-03-09 19:06 UTC, jorgkv requested changes
Kan du rebase denne på develop, så skal det fungere på ios også.

2023-03-10 09:59 UTC, amish1188 commented
oppdaterte med Øystein sitt forslag, og testet på iphone etter rebasing. Det var stas :)

2023-03-13 14:16 UTC, jorgkv requested changes

2023-03-13 14:16 UTC, jorgkv commented on src/app/core/services/search-registration/offline-capable-search-service.ts
> +      this.updateObsService.requestRefresh();
Er du sikker på at du trenger kalle requestRefresh? Vil ikke det trigge en ny sync rett etter den kjørende syncen? Hvorfor kalles det?

2023-03-13 14:16 UTC, jorgkv commented on src/app/core/services/search-registration/offline-capable-search-service.ts
>        await this.fetchAndInsertRegistrations(syncInfo);
fetchAndInsert og fetchAndDelete bør kunne kjøres samtidig. Bruk await Promise.all(...).

2023-03-13 14:16 UTC, jorgkv commented on src/app/core/services/search-registration/offline-capable-search-service.ts
> +    const { TotalMatches: appCount } = await firstValueFrom(this.SearchCount(criteria));
Disse to kallene kan kjøres samtidig, bruk Promise.all.

2023-03-13 14:17 UTC, jorgkv commented on src/app/core/services/search-registration/offline-capable-search-service.ts
> +      this.updateObsService.requestRefresh();
Så kommentaren til Øystein. Jeg syns ikke det er nødvendig å kalle requestRefresh om det presser inn en ny sync rett etter den kjørende syncen.

2023-03-13 14:34 UTC, gruble commented on src/app/core/services/search-registration/offline-capable-search-service.ts
> +      this.updateObsService.requestRefresh();
Er enig. Det var dum ide å bruke requestRefresh(). Beklager!

2023-03-14 14:10 UTC, jorgkv approved these changes

2023-03-14 14:17 UTC, merged