RO-2217:  Fjern obs fra offline db når den slettes i appen
NVE/regObs4 pull request #485
Opened 2023-03-09 12:34 UTC by amish1188

Test gjerne på begge platformer

2023-03-09 19:04 UTC, jorgkv requested changes
Kan du rebase denne på develop, så skal det fungere på ios også.

2023-03-10 09:59 UTC, amish1188 commented
funker på ios og på android

2023-03-13 13:47 UTC, gruble approved these changes

2023-03-14 09:29 UTC, jorgkv approved these changes

2023-03-14 11:35 UTC, merged