RO-1311 Logg til fil og send på epost
NVE/regObs4 pull request #50
Opened 2021-06-16 12:20 UTC by gruble

Her er første utkast til funksjon for å logge på telefon og funksjon for å sende loggfiler til oss.
Funksjonen for å sende epost ligger under meny / innstillinger / avanserte innstillinger.
Det er i hvert fall to utfordringer jeg ikke har løst:
- noen logge-kall blir ikke logget. Jeg vet ikke hvorfor, men jeg ser at konsollet i nettleser inneholder mer logging enn det som lagres på fil
- native logging til konsollet blir ikke logget. Vet ikke hvordan vi kan løse det, men fant en side hvor det sto om å fange logging til konsoll. (https://www.damirscorner.com/blog/posts/20180119-SharingConsoleLogFromIonicApps.html) Vet ikke om det kan funke, men kanskje verdt en titt?

2021-06-16 12:58 UTC, jorgkv requested changes
Ser veldig bra ut, jeg kan legge til lisensen og teste litt.

2021-06-16 12:58 UTC, jorgkv commented on src/app/modules/shared/services/logging/file-logging.service.ts
> +import {formatDate} from '@angular/common';
Tror vi må inkludere MIT-lisensen her, siden vi har kopiert koden.

2021-06-16 14:48 UTC, jorgkv commented
Jeg får ikke sendt mail når jeg tester på iPhone. Må man gjøre noe spesielt for å få åpna mailen? Kommer også vanvittig med **LOGGER_META**-greier i loggen nå, som vi burde få skrudd av - det ser litt forstyrrende ut når jeg tester via Xcode i alle fall.

2021-06-17 07:25 UTC, gruble commented
Jeg har testet på iPhone 8 nå. Logging til fil funker og send-epost-funksjonen funket også, bare jeg fikk satt opp en epost-konto på telefonen.

2021-06-17 11:12 UTC, merged