RO-2165: Bilde opplasting, kommentarer, urls på enkel vann observasjon
NVE/regObs4 pull request #524
Opened 2023-04-11 11:26 UTC by amish1188

2023-04-11 12:26 UTC, jorgkv requested changes

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
> +  autocapitalize="sentences"
Her er det feil indentering. Prøv å kjøre `npm run prettier:fix` .

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
> +  placeholder="Enter text"
Husk oversettelser.

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
> +  (ngModel)="comment"
Dette var litt uvanlig satt opp. Hvorfor bruker du ikke to-veis-binding, som vanlig med `[(ngModel)]`="..."`?

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
> +  (ngModelChange)="onChange($event)"
Du bruker ngModel i tillegg til ngModelChange, hvorfor det? Hvis det er absolutt nødvendig, legg til en kommentar som forklarer hvorfor du trenger det.

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
Hvorfor trengs comment-bar komponenten, hvorfor kan ikke text-comment som vi har allerede brukes?

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/water/simple-water-obs/simple-water-obs.component.scss
> +.inline {
Hva brukes `inline` til? Jeg kan ikke se at den blir brukt i templaten?

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/water/simple-water-obs/simple-water-obs.component.scss
> +.inline {
Gjerne legg til en kommentar om hvor den blir brukt hvis den skal være med.

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/water/simple-water-obs/simple-water-obs.component.scss
> +.inline app-numeric-input {
Samme med denne, `app-numeric-input` brukes vel ikke i templaten?

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/components/water/simple-water-obs/simple-water-obs.component.scss
> +ion-list {
Legg til en kommentar om hvorfor denne trengs.

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/pages/overview/overview.page.html
Siden vi legger til `showSimpleWaterMode` er det fint om du døper om `showSimpleMode` til `showSimpleSnowMode`

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/pages/overview/overview.page.ts
> +        if (this.showSimpleMode(draft) || draft.registration.GeoHazardTID == GeoHazard.Water) {
Hvorfor ikke bruke `showSimpleWaterMode` her?

2023-04-11 12:26 UTC, jorgkv commented on src/app/modules/registration/services/summary-item.service.ts
> +    return [];
Gjerne legg til en kommentar her om at det er fordi vi har "Enkel vannobservasjon" at det ikke er noen spesifikke summary items for vann.

2023-04-11 12:28 UTC, jorgkv commented on src/app/modules/registration/components/comment-bar/comment-bar.component.ts
> +    console.log(this.draft);
Husk å fjerne denne.

2023-04-12 07:48 UTC, widforss commented on src/app/modules/registration/components/comment-bar/comment-bar.component.html
> +  (ngModel)="comment"
Det var en del krøll med å få synket det som var lagret i databasen og det som var lagret i draften i objektet vårt. Om jeg husker rett så var det spesifikke problemet her noe med timingen med når kommentaren kom inn. Det går helt sikkert å løse på en mer elegant måte.

2023-04-12 14:07 UTC, jorgkv approved these changes
Dette ser nå bra ut, men husk å fikse den siste kommentaren før denne tas inn.

Se over commitene jeg har lagt til. Mens vi utvikler enkel vann-observasjon må vi huske å teste error-visningen av observasjonen. På den visningen skal det ikke gå an å redigere feltene:

![image](https://user-images.githubusercontent.com/8558332/231483306-d156c16f-29c7-4a8f-8e6c-32d87433ba37.png)

2023-04-12 14:07 UTC, jorgkv commented on src/app/modules/registration/components/water/simple-water-obs/simple-water-obs.component.html
> +  <!-- <app-comment-bar [registrationTid]="10" [draft]="draft"></app-comment-bar> -->
Husk å fjerne denne kommentaren

2023-04-13 07:16 UTC, merged