RO-2169: Legge til polygoner på enkel vann obs
NVE/regObs4 pull request #528
Opened 2023-04-13 09:37 UTC by amish1188

Jeg flyttet gjenbrukbare polygon funksjoner til en separat fil <b>polygon.helper.ts </b>.

Mange komponenter brukte samme style <i>{font-weight: 600;  font-size: 14px; color: #333;}</i> på label titler så jeg lagde en 
ion-label-fat klasse i <b>global.scss</b> istedenfor. 

På polygon tegning view i vann obs er kartet for kort så jeg endrer fast høyde til 64px

Jeg forenklet polygons klasser til bare en som heter PolygonsArea siden vi brukte samme verdier.

Test:
- [ ]  Inntegning av område feltet burde vises på enkel vann obs
- [ ]  Når man åpner inntegning av område burde man se å redigere flom område
- [ ]  Område burde lagres vis man bekrefter
- [ ]  Polygoner burde vises på obs kort kart
- [ ] Hvis innsending feiler man burde se Inntegning av område 'skjema' i viewet 
- [ ]  Man burde åpne de gamle vann observasjoner uten noen problemer

2023-04-24 07:16 UTC, jorgkv reviewed
Det er nok ikke ideelt at inntegning av polygon bruker en fullskjerm modal. Tilbakeknappen i nettleseren "fungerer ikke" feks. Den fungerer, men det er vanskelig å forstå hvordan siden modalen er fullskjerm.
Det burde kanskje heller vært en side med egen url. Man kan lage en ny side med ionic cli.

Jeg syns også inntegning av polygon ser veldig anonym ut:

![image](https://user-images.githubusercontent.com/8558332/233924688-f3ff4bd7-77cb-47c9-a780-392cd0295f6d.png)

Usikker på hvordan vi best løser det, jeg tror url-interfacet er laget sånn fordi det gjenbrukes eksisterende kode, men hvis "Inntegning av område"-knappen uansett er ny så kunne den kanskje fått en egen label over den også, på samme måte som url. Hør eventuelt med Atle.

2023-04-25 10:41 UTC, gruble requested changes
Funka bra. Det eneste jeg fant var en skrivefeil og en liten feil i visning av linker.

2023-04-25 10:41 UTC, gruble commented on src/assets/i18n/nb.json
> +        "SET_FLOOD_POSITION_CONFIRM": "Bekreft flom område",
flomområde

2023-04-25 10:41 UTC, gruble commented on src/app/modules/registration/components/add-web-url-item/add-web-url-item.component.html
> +    <span class="url" *ngIf="url.UrlDescription">{{ url.UrlDescription }} - {{ url.UrlLine }}</span>
Dette gjør at url'er uten beskrivelse ikke vil vises, men beskrivelse er ikke et obligatorisk felt

2023-04-25 11:11 UTC, gruble approved these changes

2023-04-25 11:40 UTC, merged