RO-2106: fikset tooltips på skjemaer
NVE/regObs4 pull request #530
Opened 2023-04-14 11:27 UTC by amish1188

Har bare gått gjennom gjenbrukbare komponenter. Det er en del felter i  forskjellige skjemaer som også kunne ha tooltips (sjekk Tester i snøobs for eksempel)

2023-04-17 11:31 UTC, gruble requested changes
I Jira-saken står det "Fjern popup siden label viser det samme som input-label.".
Det ser ut som du fortsatt viser popup/tooltip.

2023-04-18 08:13 UTC, amish1188 commented
> I Jira-saken står det "Fjern popup siden label viser det samme som input-label.". Det ser ut som du fortsatt viser popup/tooltip.

my bad. jeg leste bare tittelen og jeg trodde vi burde bare fikse oversettelser, ikke fjerne den

2023-04-24 11:40 UTC, gruble requested changes
1. Jeg tror jeg heller ville valgt "caption" som navn på propertyen. Skjønner at problemstillingen har med label å gjøre, men når du bruker en komponent (utenfra) er det (for meg i hvertfall) lettere å forstå hva "caption"  betyr enn "labelTitle".

2. Denne komponenten har fortsatt "feil" tooltip:
![image](https://user-images.githubusercontent.com/71138449/233984000-7cf888b1-03d7-4db3-be1a-b4fee4a61c95.png)

2023-04-25 10:52 UTC, gruble approved these changes

2023-04-25 10:52 UTC, merged