RO-2316: Bilde søke frontend
NVE/regObs4 pull request #534
Opened 2023-04-20 11:34 UTC by amish1188

Fungerer bare på web
Man kan søke bare bildene basert på søke kriteria. Bildene søkes etter en observasjon. Når man klikker på et bilde en modalen som viser bildet med full størrelse skal dukke opp. Man kan da navigere mellom alle bildene fra samme observasjonen. Nederst finnes en knapp som tar brukeren til /registartion side. Det er en del gjentakelser i koden (css) men jeg tror det gjør ikke noe skade. 
Bilde visning kanskje ikke ser så bra ut hvis det er bare to bilder (mye white space mellom bildene) men det vil ta mer tid å fikse en pen grid system til bildevisning, og det har vi ikke tid akkurat nå. Samme skjer på regobs.no så jeg antar at brukere er vant.

2023-04-21 07:59 UTC, gruble requested changes
Mye bra her og jeg synes det virket bra.
Fint at du legger deler opp komponentene når de "vokser", slik du gjorde med skjelettet.

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +    <app-observation-skeleton></app-observation-skeleton>
Bra du har skilt ut denne i egen komponent!

2023-04-21 07:59 UTC, gruble commented on src/assets/i18n/nb.json
> +    "NO_ATTACHMENTS": "Ingen vedlegg",
I API'et og modellene bruker vi attachment, men på klienten tror jeg vi bør kalle det bilder enn så lenge.

2023-04-21 07:59 UTC, gruble commented on src/assets/i18n/nb.json
> +    "NO_ATTACHMENTS_TEXT": "Det er ingen vedlegg funnet i kartutsnittet, forsøk å endre utsnittet eller utvid perioden du vil se observasjoner fra.",
Litt pirk:
`Det er ingen observasjoner med bilder i kartutsnittet. Forsøk....`

2023-04-21 07:59 UTC, gruble commented on src/app/pages/modal-pages/fullscreen-image-modal/fullscreen-image-modal.page.html
> +      <ion-item *ngIf="href as href" class="link-title" (click)="navigateToItem(href.url)">
Når man går tilbake etter å ha trykket på denne knappen, vises ikke de samme bildene som man så på før man klikket på bildet.
En mulighet er å åpne observasjonen i et nytt nettleservindu/tab, så man ikke mister konteksten.
Burde det ikke også vært en vanlig html-link i stedet for å navigere på click-eventet?

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +    this.viewType$.next(id);
Jeg tror ikke du trenger this.viewType. Siden this.viewType$ er et BehaviorSubject, kan du hente gjeldende visning med this.viewType$.getValue()

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +
Her var det mye gjentakelser. Hva med å lage en funksjon som tar inn 'list' eller 'grid' og filtrerer søkekriteria utfra dette? Spør meg om du ikke skjønner hva jeg mener

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +    const searchCriteriaWhenThisPageIsActiveAndViewTypeList$ = combineLatest([
Jeg ønsker meg at vi lagrer viewType som en url-parameter eller som en del av route, så vi kan gjenskape visningen man hadde.

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +  <!--We could place it in a separate component-->
God ide

2023-04-21 07:59 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +    <h3 class="ion-text-uppercase header">{{'OBSERVATION_LIST.TITLE' | translate }}</h3>
Her er det noe kluss med innrykk. Har du ikke på automatisk formatering ved lagring?

2023-04-21 07:59 UTC, gruble commented on src/assets/icon/reorder.svg
Er dette en kopi av det originale reorder-ikonet fra IonIcons?
I så fall tror jeg det er inkludert i ionic-biblioteket, så jeg tror ikke du trenger å lagre det lokalt?
Om du/dere har endret på det, foreslår jeg at du bruker et navn på ikonet som passer bedre med hva det brukes til.

2023-04-21 08:38 UTC, amish1188 commented on src/app/pages/observation-list/observation-list.page.ts
> +    this.viewType$.next(id);
kul tip!

2023-04-24 11:13 UTC, gruble requested changes
Begynner å bli veldig bra det her.
Har fortsatt noen kommentarer

2023-04-24 11:13 UTC, gruble commented on src/assets/i18n/nb.json
> +    "NO_IMAGES": "Ingen vedlegg",
Min kommentar var på teksten, ikke nøkkelen. Vi ønsker å bruke begrepet "bilder" mot brukerne, ikke "vedlegg"

2023-04-24 11:13 UTC, gruble commented on src/app/modules/shared/components/images-grid/images-grid.ts/images-grid.component.scss
> +ion-list {
- [x] På smale skjermer er det ingen marg på høyre og venstre side
- [x] Ikonene skalerer etter størrelsen på vinduet. De skal de vel ikke?
![image](https://user-images.githubusercontent.com/71138449/233924311-15e8e143-5354-4d56-9092-53a6c20b73ab.png)
- [ ] På brede skjermer, hadde det vært bedre om vi brukte hele bredden i bildevisning for å kunne se flere bilder i stedet for å begrense bredden slik vi gjør i listevisning?
![image](https://user-images.githubusercontent.com/71138449/233924630-cf2db5f6-ab9e-4e1b-a739-9245cd588d92.png)

2023-04-24 11:13 UTC, gruble commented on src/app/pages/modal-pages/fullscreen-image-modal/fullscreen-image-modal.page.ts
> +  navigateToItem(url: string) {
Trenger du denne lengre?

2023-04-24 11:13 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +    const viewTypeInParams = url.searchParams.get('viewType') as ViewType;
Url-parameter for dette funka kjempebra! Et par småting, bare:
- [ ] Brudd på OnceAndOnlyOnce. Lag en konstant for navnet på url-parameteren slik vi har gjort i SearchCriteriaService
- [ ] Jeg foreslår at parameteren heter 'view' for å gjøre url'en så enkel og kort som mulig

2023-04-24 11:13 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
> +  filterCriteriaByView(viewType: ViewType): Observable<SearchCriteriaRequestDto> {
Trenger denne være tilgjengelig utenfra?

2023-04-24 11:13 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.ts
>      this.logger.debug('Refresh', 'PagedSearchResult');
DEBUG_TAG

2023-04-24 11:13 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +          <span>{{'OBSERVATION_LIST.SORT_BY_VIEW' | translate}}:</span>
Hvorfor heter denne ledeteksten noe med sortering?

2023-04-24 11:13 UTC, gruble commented on src/app/modules/shared/components/images-grid/images-grid.ts/images-grid.component.ts
> +  @ViewChild(IonInfiniteScroll, { static: false }) scroll: IonInfiniteScroll;
Her blei det litt trangt. Hva med en blank linje før constructor?

2023-04-24 11:13 UTC, gruble commented on src/app/pages/modal-pages/fullscreen-image-modal/fullscreen-image-modal.page.html
> +        <a [href]="href.url" target="_blank"> {{ href.title | translate }}</a>
Funka bra å åpne observasjonen i nytt vindu / fane. Jeg lurer på om ikke Atle eller Ionic har et ikon som viser tydeligere at man åpner nytt vindu?
F.eks. Ionic sin open-outline?

2023-04-24 11:13 UTC, gruble commented on src/assets/i18n/nb.json
> +    "GO_TO": "Gå til observasjonen",
Bruk ubestemt form, slik som i regobs.no og som du allerede gjør på engelsk

2023-04-24 11:13 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +  <!--We could place it in a separate component-->
Både malen og klassen bak er ganske store. Jeg syntes det var en stor forbedring at du skilte ut bildevisninga i egen komponent, og skulle gjerne sett at du gjorde det samme med listevisninga. Da blir det mye lettere å vedlikeholde.

2023-04-25 12:14 UTC, gruble requested changes
Flott! Blei veldig ryddig i ObservationListPage nå etter at du skilte ut listevisning i egen komponent. 
Bare pirk igjen nå.

2023-04-25 12:14 UTC, gruble commented on src/assets/i18n/nb.json
> +    "GO_TO": "Gå til en observasjon",
Bruk "Gå til observasjon". Sorry vet jeg ba om ubestemt form, og "en observasjon" er ubestemt form, men det betyr "gå til en hvilken som helst observasjon.

2023-04-25 12:14 UTC, gruble commented on src/app/pages/observation-list/observation-list.page.html
> +  <!--We could place it in a separate component-->
Vakkert!

2023-04-25 12:14 UTC, gruble commented on src/app/modules/shared/components/list-view/list-view.component.ts
> +@Component({
Her mangler det dokumentasjon på hva denne komponenten er / brukes til

2023-04-25 12:14 UTC, gruble commented on src/app/modules/shared/components/list-view/list-view.component.ts
> +export class ListViewComponent implements OnInit {
ListViewComponent er et ganske generelt navn som kan tolkes som listevisning av hva som helst, siden denne komonenten ikke ligger under observation-list-sida.
Jeg foreslår at du beholder Observation som et prefiks til navnet

2023-04-25 12:14 UTC, gruble commented on src/app/modules/shared/components/list-view/list-view.component.ts
> +  trackByIdFunc = this.trackByIdFuncInternal.bind(this);
Hvorfor implementerer du ikke funksjonen direkte?
Det er sikkert noen gode grunner, jeg ønsker bare å forstå

2023-04-25 12:14 UTC, gruble commented on src/app/modules/shared/components/images-grid/images-grid.ts/images-grid.component.scss
> +ion-list {
Ser du har fiksa margene og ikonene, men bredden er fortsatt begrenset til 1024. Har du glemt det eller er det grunner til at du ikke vil bruker mer av bredden?

2023-04-26 08:55 UTC, gruble approved these changes

2023-04-26 10:26 UTC, merged