RO-2386: snøprofil tykkelse validering
NVE/regObs4 pull request #578
Opened 2023-07-14 12:15 UTC by amish1188

Det er en del av oppgaven. Jeg lagde validering på [backend](https://dev.azure.com/NVE-devops/Varsom%20Regobs/_git/regobs/pullrequest/3888) også

2023-08-21 14:18 UTC, gruble requested changes

2023-08-21 14:18 UTC, gruble commented on src/assets/i18n/nb.json
> +          "THICKNESS_VALIDATION": "Tykkelse kan ikke være tom eller 0",
![image](https://github.com/NVE/regObs4/assets/71138449/3d2b4675-4680-4743-9372-e093ba3b749e)
Den kan heller ikke være < 0.
Så kanskje det er enklere å skrive "Tykkelse må være mer enn 0"

2023-08-21 14:18 UTC, gruble commented on src/assets/i18n/en.json
> +          "THICKNESS_VALIDATION": "Thickness cannot be empty or 0",
Upresist. Se kommentar på norsk tekst.

2023-08-21 14:18 UTC, gruble commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness && this.layer.Thickness > 0 ? true : false;
Trenger du å lagre denne i this.isThicknessValid? 
Eller går det såpass kjapt å evaluere dette at du kan kjøre valideringsfunksjonen hver gang man skal sjekke?
Eller er det best å bruke en Subject og abonnere på denne i html?

2023-08-23 06:15 UTC, amish1188 commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness && this.layer.Thickness > 0 ? true : false;
vi ble enige om å la det være sånn

2023-08-23 07:17 UTC, gruble requested changes
Valideringa virker ikke hvis man endrer tykkelsen på et lag man allerede har registrert.
![image](https://github.com/NVE/regObs4/assets/71138449/6140ee51-cc36-430f-8808-d8aadf1c2f83)

2023-08-23 14:59 UTC, gruble requested changes
Funker bra nå, men isValid-funksjonen blei litt vanskelig å skjønne

2023-08-23 14:59 UTC, gruble commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness ? (this.layer.Thickness > 0 ? true : false) : true;
Det her begynner å bli litt vanskelig å lese. Hva med å bruke if?

2023-08-28 07:50 UTC, amish1188 commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness ? (this.layer.Thickness > 0 ? true : false) : true;
![image](https://github.com/NVE/regObs4/assets/42612597/f64281f6-13fd-4ea6-9b5b-5a0f076d8e01)
syns du det er mer lesbar?

2023-08-28 07:50 UTC, amish1188 commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness ? (this.layer.Thickness > 0 ? true : false) : true;
jeg liker ternary operator her bedre.

2023-08-28 07:56 UTC, gruble requested changes

2023-08-28 07:56 UTC, gruble commented on src/app/modules/registration/components/snow/snow-profile/strat-profile/strat-profile-layer-modal/strat-profile-layer-modal.page.ts
> +    this.isThicknessValid = this.layer.Thickness ? (this.layer.Thickness > 0 ? true : false) : true;
Jeg liker if bedre:)
NB! Feltet er obligatorisk

2023-08-29 09:40 UTC, gruble approved these changes
Nå synes jeg valideringsfunksjonen var lekker

2023-08-30 09:49 UTC, merged