RO-1953: varslingslista får nåp default tab som alle hvis koordinater ikke er gitt i urlen
NVE/regObs4 pull request #585
Opened 2023-08-21 09:27 UTC by amish1188

Jeg gjenbrukte noMapExtentAvailable metoden fra obsliste, lagt den til inn i mapService og henter observable derfra.

2023-08-22 10:04 UTC, gruble requested changes, later dismissed
1. PR'en løser problemet som er beskrevet i Jira-saken, men man kan fortsatt velge "aktuelle-fanen". Går det an å deaktivere eller skjule denne fanen, så man ikke får valgt den?

2. En annen feil eller mangel er at side for visning av varsler mister data hvis man oppfrisker nettleser, selv om vi har kartutsnitt i URL

3. En siste ting er at man går automatisk til "aktuelle-fanen" selv om man sto på "alle-fanen" og trykker oppfrisk. Vi må kanskje ha med aktiv fane som URL-parameter for at dette skal bli bra.

2023-08-23 06:18 UTC, amish1188 commented
> 1. PR'en løser problemet som er beskrevet i Jira-saken, men man kan fortsatt velge "aktuelle-fanen". Går det an å deaktivere eller skjule denne fanen, så man ikke får valgt den?
> 2. En annen feil eller mangel er at side for visning av varsler mister data hvis man oppfrisker nettleser, selv om vi har kartutsnitt i URL
> 3. En siste ting er at man går automatisk til "aktuelle-fanen" selv om man sto på "alle-fanen" og trykker oppfrisk. Vi må kanskje ha med aktiv fane som URL-parameter for at dette skal bli bra.

1. Ble løst
2. Fikset jeg men vil gjerne at Jørgen ser på den
3. Høres ut som en ekstra arbeid/separat task mulighet. Syns du jeg burde ta den i denne PRen eller opprette en ny task?

2023-08-23 07:10 UTC, gruble commented
> 3. Høres ut som en ekstra arbeid/separat task mulighet. Syns du jeg burde ta den i denne PRen eller opprette en ny task?

Du må gjerne lage en ny oppgave i Jira på dette.

2023-08-24 13:08 UTC, jorgkv requested changes
Jeg syns det ser ganske bra ut, men det er noen feil i koden som må rettes.

2023-08-24 13:08 UTC, jorgkv commented on src/app/modules/map/services/map/map.service.ts
> +  const mapView: IMapView = { bounds, center: bounds.getCenter(), zoom: null };
Hvorfor trengs denne endringen?

2023-08-24 13:08 UTC, jorgkv commented on src/app/modules/map/services/map/map.service.ts
> +    const currenteMapViewAndGeoHazards = combineLatest([this.mapView$, this.userSettingService.currentGeoHazard$]).pipe(
Hvorfor har du endret til this.mapView$?

2023-08-24 13:08 UTC, jorgkv commented on src/app/pages/observation-list/observation-list.page.ts
> +    this.disableMapExtentToggle$ = combineLatest([mapService.noMapExtentAvailable$, selectedRegionsFilterActive$]).pipe(
Fint å gjenbruke metoden her 👍

2023-08-24 13:08 UTC, jorgkv commented on src/app/modules/map/services/map/map.service.ts
> +    const currenteMapViewAndGeoHazards = combineLatest([this.mapView$, this.userSettingService.currentGeoHazard$]).pipe(
Jeg får to feil når jeg starter appen etter denne endringen

2023-08-24 13:08 UTC, jorgkv commented on src/app/pages/warning-list/warning-list.page.ts
> +      this.selectedTab = isExtent ? 'all' : 'inMapView';
Det er ikke så bra å initialisere en property som viewet forventer at eksisterer i en asynkron funksjon. Da må i så fall selectedTab endres til å være en observable i stedet. Du kan se at det forårsaker feil hvis du feks presser frem at observablen bruker litt ekstra tid ved å legge til en delay:

```typescript
mapService.noMapExtentAvailable$.pipe(delay(5000)).subscribe((isExtent) => {
  this.selectedTab = isExtent ? 'all' : 'inMapView';
  this.disableInMapViewTab = isExtent;
});
```

Linje 54 som ble fjernet bør altså fortsatt være der, eller så bør selectedTab$ endres til å være en observable.

2023-08-24 13:10 UTC, jorgkv commented on src/app/pages/warning-list/warning-list.page.ts
> +    mapService.noMapExtentAvailable$.subscribe((isExtent) => {
Savner noe dokumentasjon her som forklarer hvorfor vi trenger å håndtere dette.

2023-08-25 10:04 UTC, amish1188 commented on src/app/modules/map/services/map/map.service.ts
> +  const mapView: IMapView = { bounds, center: bounds.getCenter(), zoom: null };
sjekk kommentaren under

2023-08-25 10:04 UTC, amish1188 commented on src/app/modules/map/services/map/map.service.ts
> +    const currenteMapViewAndGeoHazards = combineLatest([this.mapView$, this.userSettingService.currentGeoHazard$]).pipe(
relevantMapChanges trigges ikke ved starten av appen (bare når jeg gjør endringene i kartet, eller åpner karte fane så det gir ingenting til varsling lista hvis man starter appen med den) derfor får jeg ikke noe mapviewareobservable som brukes av mapViewAndAreaObservable$ i mapServicen som igjen er brukt som observable i warning-list for å hente data (se warning.service linje 341). mapview trigges på starten uansett så der kan jeg hente riktig mapviewarea men da trenger jeg å kalkulere center fordi det brukes i getMapViewAreaObservable på linje 250.

har brukt filter på å sjekke om mapview eksisterer, så nå burde feilene forsvinne

2023-08-25 10:04 UTC, amish1188 commented on src/app/pages/warning-list/warning-list.page.ts
> +    mapService.noMapExtentAvailable$.subscribe((isExtent) => {
lagt til

2023-08-25 10:04 UTC, amish1188 commented on src/app/pages/warning-list/warning-list.page.ts
> +      this.selectedTab = isExtent ? 'all' : 'inMapView';
jeg satt opp inital verdi på selectedtab som inmapview

2023-08-28 13:27 UTC, jorgkv approved these changes

2023-08-28 13:46 UTC, merged