Oppdater til capacitor v6
NVE/regObs4 pull request #648
Opened 2024-04-22 12:44 UTC by jorgkv

Påkrevd oppdatering som må tas inn for å kunne rulle ut på android fra og med august.

En av commitene deaktiverer / kommenterer ut offline-registreringer ved hjelp av sqlite, siden sqlite-plugin ikke støtter capacitor 6 (enda).

Denne endringen påvirker native plugins, i alle fall capacitor-plugins. Cordova-plugins er ikke påvirket tror jeg. Vi bør derfor teste kamera, filsystem-kode (offline-kart), osv.

Har notert meg at vi bør teste kamera / legge til bilder på en android-enhet med API < 30 / mindre enn android 11.0 (i tillegg til nyere systemer selvsagt), fordi det er en annen type håndtering av bilder/kamera der.

Jeg har testet at appen starter på android-emulatorer med API 34 og 30.

2024-04-24 12:31 UTC, gruble commented
Denne blei ganske masete etter at jeg satte tlf i flymodus. Kommer opp ganske ofte:
![image](https://github.com/NVE/regObs4/assets/71138449/65f2a70d-3e3c-4b3e-b1d8-5f31aab3a7b8)

2024-04-24 12:39 UTC, gruble commented
Får til å ta bilder med kamera og ta dem rett inn i appen, men jeg får ikke til å legge til bilder fra album:
![image](https://github.com/NVE/regObs4/assets/71138449/97571d34-1231-4778-9512-fee4e16651cc)

2024-04-24 12:50 UTC, gruble commented
Fant også denne i konsollet, men tror ikke det har noe med endringer i denne PR'en å gjøre. Har laget en [egen sak](https://nveprojects.atlassian.net/browse/RO-2635) på det:
```
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null'. Current value: '0'
...
at OfflineMapPage_ion_footer_10_Template (offline-map.page.html:50:20)
```

2024-04-24 12:52 UTC, gruble requested changes
Tror jeg har testet alle plugins på min Android 12-tlf nå. 
Det eneste som ikke funka er kamera-plugin'en, så det må vi vel fikse. Hvis ikke du får til å gjenskape det, kan jeg godt se på det.

2024-04-24 13:01 UTC, gruble commented
Jeg lurer på om det er spesialtegnet %3A i filnavnet den har problemer med. Vi hadde jo en [sak](https://nveprojects.atlassian.net/browse/RO-1456) tidligere om at den ikke liker mellomrom i filnavnet? Jeg sjekker litt nærmere.
Har testet å legge til bilder fra album nå i 4.8.12 og der funker det fint.

Ser ut som det er [en del endringer i kamera-plugin'en](https://capacitorjs.com/docs/apis/camera#android) i Capacitor 6 for Android. Den funker f.eks. ikke på Android 10 og lavere, uten å legge til noen egne innstillinger i manifest-fila. Sjekket Plausible, og [vi har fortsatt en del brukere med Android 10 og lavere](https://plausible.io/regobs.no?props=%7B%22platform%22%3A%22app%22%7D&os=Android).

2024-04-26 07:12 UTC, jorgkv commented
> Ser ut som det er [en del endringer i kamera-plugin'en](https://capacitorjs.com/docs/apis/camera#android) i Capacitor 6 for Android. Den funker f.eks. ikke på Android 10 og lavere, uten å legge til noen egne innstillinger i manifest-fila. Sjekket Plausible, og [vi har fortsatt en del brukere med Android 10 og lavere](https://plausible.io/regobs.no?props=%7B%22platform%22%3A%22app%22%7D&os=Android).

Jepp, så det lar seg løse. Jeg tenkte bare det var lurt å teste på en emulator / enhet med android 10 eller lavere før vi faktisk gjorde det som står der.

2024-06-06 08:44 UTC, gruble approved these changes

2024-06-06 14:26 UTC, merged